/* Generated by scripts/generate-batch17-constellations.mjs. Do not hand-edit. */
import type {
  ConstellationEffect,
  LocalizedText,
} from "./characterConstellations";

export type Batch17ConstellationEntry = {
  gameVersion: string;
  dataAsOf: string;
  updatedAt: string;
  sourceLabel: LocalizedText;
  sourceUrl: string;
  effects: ConstellationEffect[];
};
const t = (ja: string, en: string, zh: string): LocalizedText => ({
  ja,
  en,
  "zh-CN": zh,
});
const effect = (
  level: 1 | 2 | 3 | 4 | 5 | 6,
  jaName: string,
  enName: string,
  zhName: string,
  ja: string,
  en: string,
  zh: string
): ConstellationEffect => ({
  level,
  name: t(jaName, enName, zhName),
  description: t(ja, en, zh),
});

export const BATCH_17_CHARACTER_NAMES = [
  "レザー",
  "ロサリア",
  "雲菫",
  "煙緋",
  "嘉明",
  "甘雨",
  "閑雲",
  "凝光",
  "九条裟羅",
  "荒瀧一斗",
  "刻晴",
  "珊瑚宮心海",
  "鹿野院平蔵",
  "七七",
  "重雲",
  "申鶴",
  "神里綾華",
  "神里綾人",
  "辛炎",
  "千織",
  "早柚",
  "放浪者",
  "北斗",
  "夢見月瑞希",
  "藍硯",
  "綺良々",
  "魈",
  "旅人",
] as const;

const entry1: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352606",
  effects: [
    effect(
      1,
      "狼の性",
      "Wolf's Instinct",
      "狼性",
      "レザーが元素オーブまたは原素粒子を獲得した8秒内、与えるダメージ+10％。",
      "Picking up an Elemental Orb or Particle increases Razor's DMG by 10% for 8s.",
      "雷扎获得元素球或元素粒子后，造成的伤害提高 10%，持续 8 秒。"
    ),
    effect(
      2,
      "制圧",
      "Suppression",
      "控制",
      "HPが30％以下の敵を攻撃する時、会心率+10％。",
      "Increases CRIT Rate against enemies with less than 30% HP by 10%.",
      "攻击生命值低于30%的敌人时，暴击率+10%。"
    ),
    effect(
      3,
      "獣の魂",
      "Soul Companion",
      "兽魂",
      "雷牙のスキルLv.3（最大Lv.15まで）。",
      "Increases the Level of Lightning Fang by 3.\nMaximum upgrade level is 15.",
      "Raiga技能Lv.3（最高Lv.15）。"
    ),
    effect(
      4,
      "噛みつく",
      "Bite",
      "咬",
      "鋭い爪と蒼雷の一回押しで攻撃時、命中された敵の防御力-15％、継続時間7秒。",
      "When casting Claw and Thunder (Press), enemies hit will have their DEF decreased by 15% for 7s.",
      "使用利爪攻击时，一按蓝色闪电，敌人防御力-15%，持续时间：7秒。"
    ),
    effect(
      5,
      "鋭い爪",
      "Sharpened Claws",
      "锋利的指甲",
      "鋭い爪と蒼雷のスキルLv.3（最大Lv.15まで）。",
      "Increase the Level of Claw and Thunder by 3.\nMaximum upgrade level is 15.",
      "利爪和蓝色闪电技能Lv.3（最高可达Lv.15）。"
    ),
    effect(
      6,
      "天狼",
      "Lupus Fulguris",
      "天狼",
      "10秒毎に、レザーの大剣は自動的にエネルギーを溜て次の通常攻撃で落雷を引き起こし、攻撃力100％分の雷元素ダメージを与える。雷牙状態でない時、落雷が敵に命中すると、レザーは元素スキル鋭い爪と蒼雷の雷の印を3つ獲得する。また、元素スキル鋭い爪と蒼雷を通して雷の印を獲得する時、代わりに雷の印を3つ獲得する。雷の印を消費した後の15秒間、レザーの会心率+10%、会心ダメージ+50%。",
      "Every 10s, Razor's sword charges up, causing the next Normal Attack to release lightning that deals 100% of Razor's ATK as Electro DMG.\nWhen Razor is not using Lightning Fang, a lightning strike on an enemy will grant Razor an Electro Sigil for Claw and Thunder.",
      "每10秒，皮革巨剑会自动充能，并在下一次普通攻击时造成雷击，造成攻击力100%的雷元素伤害。当闪电击中未处于雷牙状态的敌人时，雷扎将获得元素技能利爪和 3 个蔚蓝雷霆印记。另外，当通过元素技能利爪和蓝色闪电获得雷霆印记时，你将获得3个雷霆印记。消耗雷霆圣印后15秒内，皮革暴击率+10%，暴击伤害+50%。"
    ),
  ],
};

const entry2: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/364265",
  effects: [
    effect(
      1,
      "罪の導き",
      "Unholy Revelation",
      "罪恶的引导",
      "ロサリアの攻撃で会心が発生すると、攻撃速度+10%、通常攻撃のダメージ+10%、継続時間4秒。",
      "When Rosaria deals a CRIT Hit, her ATK SPD increases by 10% and her Normal Attack DMG increases by 10% for 4s.",
      "罗莎莉亚的攻击命中暴击时，攻击速度+10%，普通攻击力+10%，持续4秒。"
    ),
    effect(
      2,
      "無福の地",
      "Land Without Promise",
      "无福之地",
      "臨終の聖礼で創られる氷槍の継続時間+4秒。",
      "The duration of the Ice Lance created by Rites of Termination is increased by 4s.",
      "死亡圣礼制造的冰矛持续时间+4秒。"
    ),
    effect(
      3,
      "懺悔の儀",
      "The Wages of Sin",
      "忏悔仪式",
      "罪喰いの懺悔のスキルLv3（最大Lv.15まで）。",
      "Increases the Level of Ravaging Confession by 3.\nMaximum upgrade level is 15.",
      "噬罪者的忏悔技能Lv3（最高Lv.15）。"
    ),
    effect(
      4,
      "苦痛の恩典",
      "Painful Grace",
      "疼痛的好处",
      "罪喰いの懺悔で会心が発生すると、ロサリア自身の元素エネルギーが5回復する。この効果は、1回の罪喰いの懺悔で1度のみ発動可能。",
      "Ravaging Confession's CRIT Hits regenerate 5 Energy for Rosaria.\nCan only be triggered once each time Ravaging Confession is cast.",
      "当噬罪者告白的关键时刻，罗莎莉亚自身的元素能量恢复5点。该效果每次噬罪者告白只能激活一次。"
    ),
    effect(
      5,
      "臨終の祈り",
      "Last Rites",
      "临终祈祷",
      "臨終の聖礼のスキルLv3（最大Lv.15まで）。",
      "Increases the Level of Rites of Termination by 3.\nMaximum upgrade level is 15.",
      "死亡圣礼技能Lv3（最高Lv.15）。"
    ),
    effect(
      6,
      "代行裁判",
      "Divine Retribution",
      "替代审判",
      "臨終の聖礼を発動すると、敵の物理耐性-20%、継続時間10秒。",
      "Rites of Termination's attack decreases opponents' Physical RES by 20% for 10s.",
      "激活死亡圣礼会降低敌人20%的物理抵抗力，持续10秒。"
    ),
  ],
};

const entry3: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/366273",
  effects: [
    effect(
      1,
      "飛身趟馬",
      "Thespian Gallop",
      "飞马",
      "旋雲開相のクールタイム-18%。",
      "Opening Flourish's CD is decreased by 18%.",
      "旋风开启阶段冷却时间-18%。"
    ),
    effect(
      2,
      "諸般切末",
      "Myriad Mise-En-Scène",
      "杂项结束",
      "破嶂の旌儀発動後、周囲チーム全員の通常攻撃ダメージ+15%、継続時間12秒。",
      "After Cliffbreaker's Banner is unleashed, all nearby party members' Normal Attack DMG is increased by 15% for 12s.",
      "激活“天降神器”后，周围所有队员普通攻击力+15%，持续12秒。"
    ),
    effect(
      3,
      "牙轟探海",
      "Seafaring General",
      "轰海",
      "破嶂の旌儀のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Cliffbreaker's Banner by 3.\nMaximum upgrade level is 15.",
      "Hajime的Kei Gi的技能等级为+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "昇堂吊雲",
      "Flower and a Fighter",
      "胜道悬云",
      "雲菫が結晶、月結晶反応を起こすと防御力+20%、継続時間12秒。",
      "When Yun Jin triggers the Crystallize Reaction, her DEF is increased by 20% for 12s.",
      "云紫引起水晶或月晶反应时，防御力增加20%，持续12秒。"
    ),
    effect(
      5,
      "翹楚名坤",
      "Famed Throughout the Land",
      "翘起楚名坤",
      "旋雲開相のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Opening Flourish by 3.\nMaximum upgrade level is 15.",
      "旋云开技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "荘諧併持",
      "Decorous Harmony",
      "既尊严又和谐",
      "「飛雲旗陣」状態のキャラクターの通常攻撃の攻撃速度+12%。",
      "Characters under the effects of the Flying Cloud Flag Formation have their Normal ATK SPD increased by 12%.",
      "“飞云旗阵”状态角色普通攻击攻速+12%。"
    ),
  ],
};

const entry4: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/383108",
  effects: [
    effect(
      1,
      "法からは逃れられない",
      "The Law Knows No Kindness",
      "你无法逃脱法律的制裁",
      "煙緋が丹火の印を1枚所持するごとに、重撃を詠唱している間の中断耐性がアップ、さらに重撃のスタミナ消費-10%。",
      "When Yanfei uses her Charged Attacks,each existing Scarlet Seal additionally reduces the stamina cost of this Charged Attack by 10% and increases resistance against interruption during its release.",
      "炎希每拥有一次红印，吟唱重击时的中断抗性就会增加，重击的体力消耗-10%。"
    ),
    effect(
      2,
      "最終解釈権",
      "Right of Final Interpretation",
      "最终解释权",
      "煙緋の重撃がHP50%未満の敵に対して、会心率+20%。",
      "Increases Yanfei's Charged Attack CRIT rate by 20% against enemies below 50% HP.",
      "生命值低于50%的敌人使用烟雾猩红重击时暴击率提升20%。"
    ),
    effect(
      3,
      "真火の宝印",
      "Samadhi Fire-Forged",
      "真火宝印",
      "丹書契約のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Signed Edict by 3. Maximum upgrade level is 15.",
      "炭烧契约技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "丹書金鉄券",
      "Supreme Amnesty",
      "丹所近铁车票",
      "契約成立を発動した時、ダメージ吸収量がHP上限の45%に相当するシールドを生成する。持続時間15秒。このシールドは炎元素ダメージに対して250%の吸収効果がある。",
      "When Done Deal is used:\nCreates a shield which absorbes upto 45% of Yanfei's Max HP for 15s. This shield absorbes Pyro DMG 250% more efficiently.",
      "当你激活契约时，会产生一个吸收伤害相当于你最大生命值45%的护盾。持续时间：15 秒。该护盾可吸收 250% 的火元素伤害。"
    ),
    effect(
      5,
      "遵法誓約書",
      "Abiding Affidavit",
      "合规承诺",
      "契約成立のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Done Deal by 3.\nMaximum upgrade level is 15.",
      "签订合同技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "追加条項だよ",
      "Extra Clause",
      "这是一个附加条款。",
      "煙緋が所持できる丹火の印の最大枚数+1。",
      "Increases the maximum number of Scarlet Seals by 1.",
      "Yanhi可以拥有的Tanfire Seals的最大数量+1。"
    ),
  ],
};

const entry5: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/583327",
  effects: [
    effect(
      1,
      "瑞獣庇護",
      "Bringer of Blessing",
      "保护阿祖伊兽",
      "燦炎金猊の舞の猊獣・ウェンツァイが嘉明と合流した時、嘉明のHPを15%回復する。",
      "When the Suanni Man Chai from Suanni's Gilded Dance meets back up with Gaming, it will heal 15% of Gaming's HP.",
      "当光芒四射的金芽舞神兽文仔加入龟井时，龟井的生命值会恢复15%。"
    ),
    effect(
      2,
      "梅花踏歩",
      "Plum Blossoms Underfoot",
      "梅花脚步",
      "嘉明が治療効果を受けた時、それがHP上限を超える回復だった場合、嘉明の攻撃力+20%、継続時間5秒。",
      "When Gaming receives healing and this instance of healing overflows, his ATK will be increased by 20% for 5s.",
      "当龟井受到治疗效果时，如果恢复超过生命上限，龟井的攻击力+20%，持续5秒。"
    ),
    effect(
      3,
      "醒霊叩震",
      "Awakening Spirit",
      "觉醒精神一击",
      "瑞獣登楼のスキルLV.+3。最大Lv.15まで。",
      "Increases the Level of Bestial Ascent by 3.\nMaximum upgrade level is 15.",
      "醉菊攀爬技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "雲中越山",
      "Soar Across Mountains",
      "云中越山",
      "瑞獣登楼の落下攻撃・踏雲献瑞が敵に命中した時、嘉明の元素エネルギーを2ポイント回復する。この効果は0.2秒毎に1回のみ発動可能。",
      "When Bestial Ascent's Plunging Attack: Charmed Cloudstrider hits an opponent, it will restore 2 Energy to Gaming. This effect can be triggered once every 0.2s.",
      "醉聚攀爬的坠落攻击，桃云仙醉，击中敌人时，恢复龟井2点元素能量。该效果每0.2秒只能激活一次。"
    ),
    effect(
      5,
      "退魔咆哮",
      "Demon-Daunting Roar",
      "驱魔怒吼",
      "燦炎金猊の舞のスキルLV.+3。最大Lv.15まで。",
      "Increases the Level of Suanni's Gilded Dance by 3.\nMaximum upgrade level is 15.",
      "光焰金猪舞技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "百獣支配",
      "To Tame All Beasts",
      "野兽控制",
      "瑞獣登楼の落下攻撃・踏雲献瑞の会心率+20%、会心ダメージ+40%、攻撃範囲がアップする。",
      "Bestial Ascent's Plunging Attack: Charmed Cloudstrider CRIT Rate increased by 20% and CRIT DMG increased by 40%, and its attack radius will be increased.",
      "瑞珠攀爬的坠落攻击、桃云剑瑞的暴击率+20%、暴击伤害+40%、攻击范围增加。"
    ),
  ],
};

const entry6: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/363710",
  effects: [
    effect(
      1,
      "飲露",
      "Dew-Drinker",
      "饮露",
      "二段チャージ重撃の霜華の矢または霜華満開が命中した時、敵の氷元素耐性-15%、継続時間6秒。命中時に甘雨の元素エネルギーを2回復。二段チャージの重撃による元素エネルギーの回復効果は、1回の重撃で1度のみ発動可能。",
      "Taking DMG from a Charge Level 2 Frostflake Arrow or Frostflake Arrow Bloom decreases opponents' Cryo RES by 15% for 6s.\n\nA hit regenerates 2 Energy for Ganyu. This effect can only occur once per Charge Level Frostflake Arrow, regardless if Frostflake Arrow itself or its Bloom hit the target.",
      "两段冲锋重击霜花箭或霜花怒放命中时，敌人冰元素抗性-15%，持续6秒。命中时恢复 2 点甜雨元素能量。双蓄力重击的元素能量恢复效果每次重击只能发动一次。"
    ),
    effect(
      2,
      "獲麟",
      "The Auspicious",
      "卡琳",
      "山沢麟跡の発動可能回数+1。",
      "Trail of the Qilin gains 1 additional charge.",
      "山泽凛泽的发动次数+1。"
    ),
    effect(
      3,
      "雲行",
      "Cloud-Strider",
      "云线",
      "降衆天華のスキルLv.+3。",
      "Increases the Level of Celestial Shower by 3. Maximum upgrade level is 15.",
      "降天花技能等级+3。"
    ),
    effect(
      4,
      "西狩",
      "Westward Sojourn",
      "西狩",
      "降衆天華エリア内、敵の受けるダメージが増加する。受けるダメージの増加量は初期が5%、3秒毎に5%上昇し、最大25%まで上昇する。エリアを出た跡、継続時間3秒。",
      "Opponents standing within the AoE of Celestial Shower take increased DMG. This effect strengthens over time. Increased DMG taken begins at 5% and increases by 5% every 3s, up to a maximum of 25%.\nThe effect lingers for 3s after the opponent leaves the AoE.",
      "降天花区域内的敌人受到的伤害增加。受到的伤害量初始为5%，每3秒增加5%，最大增加到25%。痕迹离开该区域，持续时间 3 秒。"
    ),
    effect(
      5,
      "折草",
      "The Merciful",
      "织草",
      "山沢麟跡のスキルLv.+3。",
      "Increases the Level of Trail of the Qilin by 3. Maximum upgrade level is 15.",
      "山泽凛人的技能等级+3。"
    ),
    effect(
      6,
      "履虫",
      "The Clement",
      "足虫",
      "山沢麟跡を発動すると、30秒以内に放つ最初の霜華の矢が、チャージせずに発動可能になる。",
      "Using Trail of the Qilin causes the next Frostflake Arrow shot within 30s to not require charging.",
      "激活山泽临济后，30秒内发射的第一支霜花箭无需蓄力即可激活。"
    ),
  ],
};

const entry7: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/583326",
  effects: [
    effect(
      1,
      "因縁を晴らす借風",
      "Purifying Wind",
      "借来的风，清理命运",
      "朝翔の鶴雲の使用可能回数+1。",
      "White Clouds at Dawn gains 1 additional charge.",
      "安里的鹤云可以使用+1。"
    ),
    effect(
      2,
      "俗世を離れた鶴鳴",
      "Aloof From the World",
      "远离尘世的鹤目",
      "朝翔の鶴雲の天梯昇りを発動後、閑雲の攻撃力+20%、継続時間15秒。また、固有天賦「思えば洞中の仙人であるべし」の効果は以下のように強化される。夕集の竹星の「竹星」の補助仙力が残っている時、周囲のフィールド上キャラクターの着地時の落下攻撃によるダメージが、閑雲の攻撃力の400%分アップする。この方法によって、近くのフィールド上キャラクターの着地時の落下攻撃は最大18000までダメージアップ可能。1回の着地における落下攻撃ダメージでは、上記ダメージアップ効果は1体の敵にのみ適用される。各キャラクターごとに、0.4秒毎に1回のみ発動可能。この効果を有効にするには固有天賦「思えば洞中の仙人であるべし」を解放する必要がある。",
      'After using a Skyladder from White Clouds at Dawn, Xianyun\'s ATK will be increased by 20% for 15s.\nAdditionally, the effects of the Passive Talent "Consider, the Adeptus in Her Realm" will be enhanced: When the Starwicker created by Stars Gather at Dusk has Adeptal Assistance stacks, nearby active characters\' Plunging Attack shockwave DMG will be increased by 400% of Xianyun\'s ATK. The maximum DMG increase that can be achieved this way is 18,000.\nEach Plunging Attack shockwave DMG instance can only apply this increased DMG effect to a single opponent. Each character can trigger this effect once every 0.4s.\n\nYou must first unlock the Passive Talent "Consider, the Adeptus in Her Realm."',
      "激活安里的鹤云天梯飞升后，袋鼠的攻击力+20%，持续15秒。此外，独特天赋“如果你想一想，你应该是山洞里的隐士”的效果将如下加强。当羽州武清的“武清”辅助力剩余时，场上周围角色落地时坠落攻击所造成的伤害将增加卡努攻击力的400%。通过此方法，附近场上角色落地时的坠落攻击伤害最高可提升至18000点。对于一次落地造成的攻击伤害，上述伤害增加效果仅适用于一名敌人。每个角色每 0.4 秒只能激活一次。要激活这个效果，需要解锁独特的天赋“如果你仔细想想，你应该是山洞里的隐士。”"
    ),
    effect(
      3,
      "造化に在りし星月",
      "Creations of Star and Moon",
      "存在于造物中的星星和月亮",
      "夕集の竹星のスキルLV.+3。最大Lv.15まで。",
      "Increases the Level of Stars Gather at Dusk by 3.\nMaximum upgrade level is 15.",
      "玉树武星的技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "黍珠割烹の妙",
      "Mystery Millet Gourmet",
      "三重割烹的奇观",
      "1回の朝翔の鶴雲での鶴雲幻化中、天梯昇りを1/2/3回発動すると、その幻化状態の間、閑雲衝撃波が敵に命中した時に周囲のチーム全員のHPを回復する。回復量はそれぞれ、閑雲の攻撃力の50%/80%/150%に相当。この効果は5秒毎に1回のみ発動可能。",
      "After using Skyladder 1/2/3 times during one White Clouds at Dawn Cloud Transmogrification state, when a Driftcloud Wave unleashed during that instance hits an opponent, it will heal all nearby party members for 50%/80%/150% of Xianyun's ATK. This effect can be triggered once every 5s.",
      "如果在安里的鹤云幻境中开启天梯飞升1/2/3次，在该幻境状态下，当鹤云冲击波击中敌人时，周围所有队员的生命值都会恢复。恢复量分别相当于康古莫攻击力的50%/80%/150%。该效果每 5 秒只能激活一次。"
    ),
    effect(
      5,
      "彩雲を巡りし足取",
      "Astride Rose-Colored Clouds",
      "西云周边散步",
      "朝翔の鶴雲のスキルLV.+3。最大Lv.15まで。",
      "Increases the Level of White Clouds at Dawn by 3.\nMaximum upgrade level is 15.",
      "安里的鹤云技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "留雲を仙と覚る",
      "Cloudkeeper's Spirit",
      "一觉醒来，鲁恩变成了仙女",
      "1回の朝翔の鶴雲での鶴雲幻化中、天梯昇りを1/2/3回発動すると、その幻化状態の間、閑雲衝撃波の会心ダメージが15%/35%/70%アップする。閑雲が夕集の竹星を発動した後の16秒間、朝翔の鶴雲がクールタイムに入らなくなる。この効果は関雲が朝翔の鶴雲を8回発動すると解除される。",
      "After Xianyun uses 1/2/3 Skyladders within one Cloud Transmogrification caused by White Clouds at Dawn, the CRIT DMG of a Driftcloud Wave created in this instance of Cloud Transmogrification will be increased by 15%/35%/70%.\nWithin 16s after Xianyun has used Stars Gather at Dusk, White Clouds at Dawn will not enter CD. This effect will be canceled once she has used White Clouds at Dawn 8 times.",
      "如果在鹤云幻境期间，使用安里的鹤云发动一次天梯飞升1/2/3次，该幻境状态下鹤云冲击波的暴击伤害将增加15%/35%/70%。康云激活玉树的武星后16秒内，安里的鹤云将不再进入冷却。当赤云发动安里的鹤云 8 次时，该效果会被取消。"
    ),
  ],
};

const entry8: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352617",
  effects: [
    effect(
      1,
      "散る星の破片",
      "Piercing Fragments",
      "散落的星星碎片",
      "通常攻撃が命中すると範囲ダメージを与える。",
      "When a Normal Attack hits, it deals AoE DMG.",
      "当普通攻击命中时，会造成范围伤害。"
    ),
    effect(
      2,
      "璇璣、崑崙を鎮める",
      "Shock Effect",
      "仙姬平定昆仑",
      "璇璣屏が破壊した時、クールタイムがリセットする。6秒毎に1回のみ発動可能。",
      "When Jade Screen is shattered, its CD will reset.\nCan occur once every 6s.",
      "当璇玑屏被摧毁时，冷却时间将会重置。每 6 秒只能激活一次。"
    ),
    effect(
      3,
      "森羅星列の囲い",
      "Majesty be the Array of Stars",
      "神罗星空围场",
      "天権崩玉のスキルLv.3（最大Lv.15まで）。",
      "Increases the Level of Starshatter by 3.\nMaximum upgrade level is 15.",
      "天言工业技能Lv.3（最高Lv.15）。"
    ),
    effect(
      4,
      "神機妙道の陣組み",
      "Exquisite be the Jade, Outshining All the Beneath",
      "神机妙道的形成",
      "璇璣屏付近のキャラクターの全元素耐性+10％。",
      "Jade Screen increases nearby characters' Elemental RES by 10%.",
      "璇玑屣附近人物所有元素抗性+10%。"
    ),
    effect(
      5,
      "瓊屏と千扇の守り",
      "Invincible be the Jade Screen",
      "琼折屏千扇护",
      "璇璣屏のスキルLv.3（最大Lv.15まで）。",
      "Increase the Level of Jade Screen by 3.\nMaximum upgrade level is 15.",
      "玄圭屏技能Lv.3（最高Lv.15）。"
    ),
    effect(
      6,
      "燦々たる七星",
      "Grandeur be the Seven Stars",
      "七颗璀璨的星星",
      "天権崩玉を放つ時、凝光は七枚の星璇を生成する。",
      "When Starshatter is used, Ningguang gains 7 Star Jades.",
      "天力球释放时，凝聚的光芒产生了七颗星辰。"
    ),
  ],
};

const entry9: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/395525",
  effects: [
    effect(
      1,
      "烏目",
      "Crow eyes",
      "乌鸦眼",
      "天狗呪雷はキャラクターに攻撃力アップ効果を付与し、または敵に命中すると、烏天狗雷霆召呪のクールタイム-1秒。この効果は3秒毎に1回のみ発動可能。",
      "Tengu Curse Rai gives the character an attack power increase effect, or if it hits an enemy, the cooldown of Karasu Tengu Thunder Summoning Curse is reduced by 1 second. This effect can only be activated once every 3 seconds.",
      "天狗咒雷给予角色攻击力增加效果，或者击中敌人时，卡尔土天狗召唤雷咒的冷却时间减少1秒。该效果每3秒只能发动一次。"
    ),
    effect(
      2,
      "鴉の羽",
      "raven feathers",
      "乌鸦羽毛",
      "烏天狗雷霆召呪を発動した時、九条裟羅が元々いた位置に微弱な天狗呪雷・伏の「烏羽」を発動し、本来の30%のダメージを与える。",
      'When the Karasu Tengu Thunder Summoning spell is activated, a weak Tengu curse lightning called "Carasuha" is activated in the position where Kujo Sara was originally, dealing 30% of the original damage.',
      "乌条天狗召唤雷魔法发动时，九条纱罗原来所在的位置会触发一道名为“乌条叶”的微弱天狗诅咒闪电，造成原来伤害的30%。"
    ),
    effect(
      3,
      "心魔",
      "heart demon",
      "心魔",
      "煌煌千道鎮式のスキルLv.+3。最大Lv.15まで。",
      "Kiraki Sendo Chinshiki skill level +3. Up to maximum Lv.15.",
      "Kiraki Sendo Chinshiki技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "徹証",
      "Thorough proof",
      "充分证明",
      "煌煌千道鎮式による天狗呪雷・雷礫の数が6つに増加する。",
      "The number of Tengu Cursed Thunder and Thunder Stones created by Kouki Sendo Chinshiki increases to 6.",
      "仙道光辉创造的天狗咒雷和雷石的数量增加到6个。"
    ),
    effect(
      5,
      "呪詠",
      "Curse",
      "诅咒",
      "烏天狗雷霆召呪のスキルLv.+3。最大Lv.15まで。",
      "Karasu Tengu Thunder Summoning Skill Lv. +3. Up to maximum Lv.15.",
      "卡尔土天狗召唤雷技Lv. +3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "我界",
      "My world",
      "我的世界",
      "天狗呪雷による攻撃力アップ状態のキャラクターは、雷元素ダメージの会心ダメージ+60%。",
      "Characters whose attack power is increased by Tengu Curse will receive +60% critical damage from lightning elemental damage.",
      "受到天狗咒攻击力提升的角色，雷属性伤害暴击伤害+60%。"
    ),
  ],
};

const entry10: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/407413",
  effects: [
    effect(
      1,
      "知らぬなら、聞かせてやろう",
      "Stay a While and Listen Up",
      "如果您不知道，请告诉我",
      "最凶鬼王・一斗轟臨！！発動後、荒瀧一斗は「乱神の怪力」効果を2層獲得する。発動1秒後、1.5秒の間、荒瀧一斗は0.5秒毎に「乱神の怪力」効果をさらに1層獲得する。",
      "Royal Descent: Behold, Itto the Evil!, Arataki Itto gains 2 stacks of Superlative Superstrength. After 1s, Itto will gain 1 stack of Superlative Superstrength every 0.5s for 1.5s.",
      "最邪恶的魔王一斗来了！ ！激活后，新泷和人获得2层“怒神神通”效果。发动后1秒，新泷和人每0.5秒额外获得一层“怒神神力”效果，持续1.5秒。"
    ),
    effect(
      2,
      "衆よ集いて、山岳倒し",
      "Gather 'Round, It's a Brawl!",
      "人们聚集起来，战胜高山。",
      "最凶鬼王・一斗轟臨！！を発動した後、チーム内に岩元素タイプキャラクターが1人いる毎に、クールタイム-1.5秒、荒瀧一斗の元素エネルギーを6ポイント回復する。この方式で短縮できるクールタイムは4.5秒までとなり、回復できる元素エネルギーは18ポイントまでとなる。",
      "Geo will decrease that skill's CD by 1.5s and restore 6 Energy to Arataki Itto. CD can be decreased by up to 4.5s in this manner. Max 18 Energy can be restored in this manner.",
      "最邪恶的魔王一斗来了！ ！激活后，队伍中每有一个岩系角色，荒泷和人的元素能量就会恢复6点，冷却时间为-1.5秒。通过这种方法，冷却时间可以缩短到4.5秒，并且可以恢复的元素能量高达18点。"
    ),
    effect(
      3,
      "牛王跨げば、水陸自在",
      "Horns Lowered, Coming Through",
      "如果跨过潮，就可以自由地在陆地或水上旅行。",
      "魔殺絶技・岩牛発破！のスキルLv.+3。最大Lv.15まで。",
      "Masatsu Zetsugi: Akaushi Burst! by 3. Maximum upgrade level is 15.",
      "杀妖术：岩牛爆！技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "奉行牢獄、御食事処",
      "Jailhouse Bread and Butter",
      "治安监狱、餐厅",
      "最凶鬼王・一斗轟臨！！による「憤怒の鬼王」状態が終了すると、周囲チーム全員の防御力+20％、攻撃力+20％、継続時間10秒。",
      "When the Raging Oni King state caused by Royal Descent: Behold, Itto the Evil! ends, all nearby party members gain 20% DEF and 20% ATK for 10s.",
      "最邪恶的魔王一斗来了！ ！ “愤怒魔王”状态结束时，周围所有队员防御力+20%，攻击力+20%，持续10秒。"
    ),
    effect(
      5,
      "花坂十年、轟く我が名",
      "10 Years of Hanamizaka Fame",
      "花坂十年，我的名字呼啸",
      "最凶鬼王・一斗轟臨！！のスキルLv.+3。最大Lv.15まで。",
      "Royal Descent: Behold, Itto the Evil! by 3. Maximum upgrade level is 15.",
      "最邪恶的魔王一斗来了！ ！技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "傾奇の張本、荒瀧一斗",
      "Arataki Itto, Present!",
      "古怪的张本、新泷和人",
      "荒瀧一斗の重撃の会心ダメージ+70%。また、「荒瀧逆袈裟」を発動するとき、50％の確率で「乱神の怪力」が消費されなくなる。",
      "Arataki Itto's Charged Attacks deal +70% Crit DMG. Additionally, when he uses Arataki Kesagiri, he has a 50% chance to not consume stacks of Superlative Superstrength.",
      "新泷和人的重击暴击伤害+70%。另外，发动“荒泷玉草”时，有50%的概率不消耗“乱神超人之力”。"
    ),
  ],
};

const entry11: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352626",
  effects: [
    effect(
      1,
      "迅雷",
      "Thundering Might",
      "快速闪电",
      "雷楔継続中に再び星辰帰位を発動すると刻晴は消失と出現位置に攻撃力の50％の雷範囲ダメージを与える。",
      "Recasting Stellar Restoration while a Lightning Stiletto is present causes Keqing to deal 50% of her ATK as AoE Electro DMG at the start point and terminus of her Blink.",
      "如果在雷鬼继续时再次激活青神归来，时春将会消失，并对他出现的位置造成攻击力 50% 的闪电范围伤害。"
    ),
    effect(
      2,
      "苛捐",
      "Keen Extraction",
      "刺激",
      "刻晴の通常攻撃と重撃が雷元素の影響を受けた敵に命中した時、50％の確率で原素粒子を1個生成する。5秒毎に1回のみ発動可能。",
      "When Keqing's Normal and Charged Attack's hit enemies affected by Electro, they have a 50% chance of producing an Elemental Particle. This effect can only occur once every 5s.",
      "时晴的普通攻击和重击击中受到雷元素影响的敌人时，有50%的概率产生1个元素粒子。每 5 秒只能激活一次。"
    ),
    effect(
      3,
      "登楼",
      "Forseen Reformation",
      "爬上塔楼",
      "天街巡遊のスキルLv.+3。",
      "Increases the Level of Starward Sword by 3.\nMaximum upgrade level is 15.",
      "天游技能Lv. +3。"
    ),
    effect(
      4,
      "調律",
      "Attunement",
      "调音",
      "刻晴が雷元素の関連反応を起こした10秒間、攻撃力+25％。",
      "For 10s after Keqing triggers an Electro-related Elemental Reaction, her ATK is increased by 25%.",
      "时春与雷属性反应时，攻击力+25%，持续10秒。"
    ),
    effect(
      5,
      "移燈",
      "Beckoning Stars",
      "移动光",
      "星辰帰位のスキルLv.+3。",
      "Increase the Level of Stellar Restoration by 3.\nMaximum upgrade level is 15.",
      "星回技能Lv. +3。"
    ),
    effect(
      6,
      "廉貞",
      "Tenacious Star",
      "诚实",
      "通常攻撃、重撃、元素スキルまたは元素爆発を発動する時、刻晴の与える雷ダメージ+6％、継続時間8秒。通常攻撃、重撃、元素スキルまたは元素爆発の発動による効果はそれぞれ別々でカウントされる。",
      "When initiating a Normal Attack, Charged Attack, Elemental Skill or Elemental Burst, Keqing gains a 6% Electro DMG Bonus for 8s. Effects triggered by Normal Attacks, Charged Attacks, Elemental Skills and Elemental Bursts are considered independent entities.",
      "发动普通攻击、重击、元素技能、元素爆炸时，时春的雷电伤害增加6%，持续8秒。普通攻击、重击、元素技能、元素爆炸发动的效果分别计算。"
    ),
  ],
};

const entry12: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/395524",
  effects: [
    effect(
      1,
      "水に渓に決する",
      "At Water's Edge",
      "由水决定",
      "海人の羽衣による「儀来羽衣」状態の時、珊瑚宮心海の通常攻撃の最後の一撃は追加で遊魚を一匹召喚し、珊瑚宮心海のHP上限30％分の水元素ダメージを与える。このダメージは通常攻撃ダメージとみなされない。",
      "While donning the Ceremonial Garment created by Nereid's Ascension, the final Normal Attack in Sangonomiya Kokomi's combo will unleash a swimming fish to deal 30% of her Max HP as Hydro DMG.\nThis DMG is not considered Normal Attack DMG.",
      "羽衣快斗处于“气来羽衣”状态时，新海三乡宫普通攻击的最后一击会额外召唤一条鱼，并造成三乡宫新海最大生命值30%的水元素伤害。该伤害不被视为普通攻击伤害。"
    ),
    effect(
      2,
      "雲海の波立ち",
      "The Clouds Like Waves Rippling",
      "云海里的涟漪",
      "珊瑚宮心海のHP上限を基準に、HP50%以下のキャラクターに対し、以下の方式により回復量がアップする。・海月の誓いの化海月：HP上限の4.5%・海人の羽衣の通常攻撃と重撃：HP上限の0.6%。",
      "Sangonomiya Kokomi gains the following Healing Bonuses with regard to characters with 50% or less HP via the following methods:\nKurage's Oath Bake-Kurage: 4.5% of Kokomi's Max HP.\nNereid's Ascension Normal and Charged Attacks: 0.6% of Kokomi's Max HP.",
      "以三宫新海的生命上限为基础，生命值在50%以下的角色，恢复量将按以下方法增加。 ・海月的誓言变身海月：生命值上限的4.5% ・马和羽衣的普通攻击和重击：生命值上限的0.6%。"
    ),
    effect(
      3,
      "月舟露渚",
      "The Moon, A Ship O'er the Seas",
      "月船海滩",
      "海人の羽衣のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Nereid's Ascension by 3.\nMaximum upgrade level is 15.",
      "羽衣快斗技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "月に摂す千の川",
      "The Moon Overlooks the Waters",
      "一千条河流滋养着月亮",
      "海人の羽衣による儀来羽衣状態の時、珊瑚宮心海の通常攻撃の攻撃速度+10%。そして通常攻撃が敵に命中すると、元素エネルギーを0.8ポイント回復する。この効果は0.2秒毎に1回のみ発動可能。",
      "While donning the Ceremonial Garment created by Nereid's Ascension, Sangonomiya Kokomi's Normal Attack SPD is increased by 10%, and Normal Attacks that hit opponents will restore 0.8 Energy for her.\nThis effect can occur once every 0.2s.",
      "因羽衣快斗而处于气来羽衣状态时，新海三乡宫的普通攻击攻击速度+10%。并且普通攻击击中敌人时，会恢复0.8点元素能量。该效果每0.2秒只能激活一次。"
    ),
    effect(
      5,
      "百川集海",
      "All Streams Flow to the Sea",
      "百川修会",
      "海月の誓いのスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Kurage's Oath by 3.\nMaximum upgrade level is 15.",
      "海月誓言技能Lv. +3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "珊瑚一心",
      "Sango Isshin",
      "三乡一心",
      "海人の羽衣による儀来羽衣状態の時、珊瑚宮心海の通常攻撃または重撃でHP80%以上のキャラクターに治癒を行うと、水元素ダメージ+40%。継続時間4秒。",
      "While donning the Ceremonial Garment created by Nereid's Ascension, Sangonomiya Kokomi gains a 40% Hydro DMG Bonus for 4s after her Normal and Charged Attacks heal a character with 80% or more HP.",
      "因羽衣快斗而进入气来羽衣状态时，新海三乡宫的普通攻击或重击治愈生命值80%以上的角色，水属性伤害增加40%。持续时间：4 秒。"
    ),
  ],
};

const entry13: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/455161",
  effects: [
    effect(
      1,
      "通称少年事件簿",
      "Named Juvenile Casebook",
      "俗称少年案件卷宗",
      "鹿野院平蔵が登場してから5秒間、通常攻撃の攻撃速度+15%、また戮心拳の「変格」効果を1層獲得する。この効果は10秒毎に1回のみ発動可能。",
      "For 5s after Shikanoin Heizou takes the field, his Normal Attack SPD is increased by 15%. He also gains 1 Declension stack for Heartstopper Strike. This effect can be triggered once every 10s.",
      "六之院平藏出现后5秒内，普通攻击的攻击速度增加15%，并且获得升神剑的“变身”效果1层。该效果每10秒只能发动一次。"
    ),
    effect(
      2,
      "真相究明捜査集",
      "Investigative Collection",
      "真相调查收集",
      "廻風蹴で生成した捕縛の風穴による引き寄せ効果が強化され、継続時間が延長され1秒になる。",
      "The pull effect of the Arresting Windtunnel created by Windmuster Kick is enhanced, and its duration is increased to 1s.",
      "海风踢产生的风洞的牵引效果强化，持续时间延长至1秒。"
    ),
    effect(
      3,
      "暗号隠語難問集",
      "Esoteric Puzzle Book",
      "代码俚语拼图合集",
      "戮心拳のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Heartstopper Strike by 3.\nMaximum upgrade level is 15.",
      "血拳技能Lv. +3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "荒唐無稽百物語",
      "Tome of Lies",
      "100个荒诞故事",
      "一回の廻風蹴で発生した「廻風真眼」が初めて爆発する時、鹿野院平蔵自身の元素エネルギーを9回復する。その後、爆発するたびに追加で元素エネルギーを1.5回復する。この方法により一回の廻風蹴で回復できる元素エネルギーは、最大13.5まで",
      "The first Windmuster Iris explosion in each Windmuster Kick will regenerate 9 Elemental Energy for Shikanoin Heizou. Every subsequent explosion in that Windmuster Kick will each regenerate an additional 1.5 Energy for Heizou.\nOne Windmuster Kick can regenerate a total of 13.5 Energy for Heizou in this manner.",
      "当一次海风踢产生的“海风新岩”第一次爆炸时，会恢复乐之院平三自身的9点元素能量。之后，每次爆炸都会额外恢复1.5点元素能量。通过这种方法，凯夫一脚能够恢复的元素能量高达13.5。"
    ),
    effect(
      5,
      "屏禁密室大図鑑",
      "Secret Archive",
      "密室百科",
      "廻風蹴のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Windmuster Kick by 3.\nMaximum upgrade level is 15.",
      "海夫踢技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "奇想天外捕物帳",
      "Curious Casefiles",
      "奇妙的陷阱书",
      "戮心拳を発動する時、戮心拳の会心率が「変格」の層数ごとに4％アップする。「正論」効果が付与されている場合、戮心拳の会心ダメージは32%アップする。",
      "Each Declension stack will increase the CRIT Rate of the Heartstopper Strike unleashed by 4%. When Heizou possesses Conviction, this Heartstopper Strike's CRIT DMG is increased by 32%.",
      "激活杀戮拳时，每“变”一层，杀戮拳的暴击率增加4%。如果附加“正义”效果，死亡之拳的暴击伤害增加32%。"
    ),
  ],
};

const entry14: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-09-08",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352624",
  effects: [
    effect(
      1,
      "寒苦回向",
      "Ascetics of Frost",
      "寒苦复归",
      "寒病鬼差が度厄のお礼マークのついた敵に命中した時、七七の元素エネルギーを2回復する。輝映・星閃：寒病鬼差の攻撃および追加攻撃が敵に命中した時、七七の元素エネルギーを6回復する。この効果は6秒ごとに最大1回まで発動可能。",
      "When the Herald of Frost hits an enemy marked by a Fortune-Preserving Talisman, Qiqi regenerates 2 Energy.",
      "当冷魔差用感谢符击中敌人时，它会恢复七七的 2 点元素能量。辉影/星泉：寒魔异类攻击及追加攻击击中敌人时，恢复七七的元素能量6点。该效果最多每 6 秒激活一次。"
    ),
    effect(
      2,
      "氷寒蝕骨",
      "Frozen to the Bone",
      "冰冷的骨头",
      "氷元素の影響を受けた敵に、七七の通常攻撃と重撃の与えるダメージ+15％。輝映・星閃：七七の攻撃力+50%。",
      "Qiqi's Normal and Charge Attack DMG against enemies affected by Cryo is increased by 15%.",
      "七七对受到冰属性影响的敌人的普通攻击和重击伤害增加15%。 Kaerei/Hoshisen：七七的攻击力+50%。"
    ),
    effect(
      3,
      "昇天宝詰",
      "Ascendant Praise",
      "侯祖姆阿森松酒店",
      "仙法・救苦度厄のスキルLv.3（最大Lv.15まで）。",
      "Increases the Level of Adeptus Art: Preserver of Fortune by 3.\nMaximum upgrade level is 15.",
      "不朽/救赎和不幸的技能等级3（最高等级15）。"
    ),
    effect(
      4,
      "天威圧衆",
      "Divine Suppression",
      "天威恐人群",
      "度厄のお札でマークされたターゲットの攻撃力-20%。さらに、度厄のお札の治癒効果が発動した時、追加で1回付近にいるHP割合が最も低いキャラクターのHPを回復する。回復量は七七の攻撃力の180%に相当する。",
      "Targets marked by the Fortune-Preserving Talisman have their ATK decreased by 20%.",
      "带有邪恶护身符的目标的攻击力-20%。另外，度符的治疗效果启动时，会额外恢复附近生命百分比最低的角色的生命值。恢复量相当于七七攻击力的180%。"
    ),
    effect(
      5,
      "紅蓮開花",
      "Crimson Lotus Bloom",
      "深红色的花",
      "仙法・寒病鬼差のスキルLv.3（最大Lv.15まで）。",
      "Increase the Level of Adeptus Art: Herald of Frost by 3.\nMaximum upgrade level is 15.",
      "Senpo和冷魔的技能Lv.3（最高Lv.15）区别。"
    ),
    effect(
      6,
      "起死回骸",
      "Rite of Resurrection",
      "尸体",
      "仙法・救苦度厄を発動する時、周囲にいるチーム全員の戦闘不能状態を解除し、HPを50%まで回復する。この効果は15分ごとに1回のみ発動可能。また、仙法・救苦度厄を発動した後、七七はさらに4層の洞玄を獲得し、チーム内の自身の現在のフィールド上キャラクター(七七を除く)が天賦やスキルによって直接星電導または星拡散ダメージを与えた時、洞玄を1層消費して、その与えるダメージを七七の攻撃力の600%分アップする。洞玄の継続時間は最大12秒。仙法・救苦度厄を発動した時、層数が更新される。",
      "Using Adeptus Art: Preserve of Fortune revives all nearby fallen characters and regenerates 50% of their HP.\nThis effect can only occur once every 15 mins.",
      "激活不朽法术/拯救度时，消除周围小队所有成员的无力状态，并恢复生命值50%。该效果每15分钟只能发动一次。另外，激活不死/救赎度邪恶后，七七将额外获得4层道元，当前场上的角色（不包括七七）使用天赋或技能直接造成星辰传导或星辰扩散伤害时，将消耗一层道元，造成的伤害增加七七攻击力的600%。豆元的持续时间长达 12 秒。当您激活童话/救赎程度邪恶时，层数将会更新。"
    ),
  ],
};

const entry15: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352621",
  effects: [
    effect(
      1,
      "釈凌詠氷",
      "Ice Unleashed",
      "释良英兵卫",
      "通常攻撃の最後の一撃が全員に3つの氷の刃を放ち、氷の刃は途中の敵に重雲の50％攻撃力の氷ダメージを与える。",
      "The last attack of Chongyun's Normal Attack combo releases 3 ice blades. Each blade deals 50% of Chongyun's ATK as Cryo DMG to all enemies in its path.",
      "普通攻击的最后一击向所有人释放3道冰刃，冰刃对途中敌人造成相当于巨古莫攻击力50%的冰属性伤害。"
    ),
    effect(
      2,
      "周天の回転",
      "Atmospheric Revolution",
      "天地旋转",
      "霊刃・重華積霜エリア内、元素スキルと元素爆発のクールタイム-15％。",
      "Elemental Skills and Elemental Bursts cast within the Frost Field created by Spirit Blade - Chongyun's Layered Frost have their CD time decreased by 15%.",
      "灵刃/尤卡冰霜区域的元素技能和元素爆炸冷却时间-15%。"
    ),
    effect(
      3,
      "雲の果てに光あり",
      "Cloudburst",
      "云层尽头有光",
      "霊刃・雲開星落のスキルLv.3（最大Lv.15まで）。",
      "Increases the Level of Spirit Blade - Cloud-parting Star by 3.\nMaximum upgrade level is 15.",
      "灵刀/开云星陨技能Lv.3（最高可达Lv.15）。"
    ),
    effect(
      4,
      "浮雲霜天",
      "Frozen Skies",
      "浮云霜天",
      "重雲の全ての攻撃が氷元素の影響を受けた敵に命中した時、自身の元素エネルギーを1回復。この効果は2秒毎に1回のみ発動可能。",
      "Chongyun regenerates 1 Energy every time he hits an enemy affected by Cold or Frozen status effects.\nThis effect can only occur once every 2s.",
      "当巨古莫的所有攻击击中受到冰元素影响的敌人时，他会恢复 1 点元素能量。该效果每2秒只能发动一次。"
    ),
    effect(
      5,
      "真道の正理",
      "The True Path",
      "真理的真理",
      "霊刃・重華積霜のスキルLv.3（最大Lv.15まで）。",
      "Increases the level of Spirit Blade - Chongyun's Layered Frost by 3.\nMaximum upgrade level is 15.",
      "灵刃/下十花技能Lv.3（最高Lv.15）。"
    ),
    effect(
      6,
      "四霊の捧げ",
      "Rally of Four Blades",
      "四灵的供奉",
      "霊刃・雲開星落がHPの百分率が重雲より低い時に命中した時、ダメージ+15％。その他、使用する時にさらに追加で霊刃を1本召喚する。",
      "Spirit Blade - Cloud-parting Star deals 15% more DMG to enemies with a lower percentage of their Max HP remaining than Chongyun.\nThis skill will also summon 1 additional spirt blade.",
      "灵刀云开星陨命中时，生命百分比低于重云时，伤害+15%。此外，使用时还会召唤一把额外的灵刃。"
    ),
  ],
};

const entry16: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/415138",
  effects: [
    effect(
      1,
      "心斎",
      "Clarity of Heart",
      "心斋",
      "仰霊威召将役呪の使用可能回数+1",
      "Spring Spirit Summoning can be used 1 more time.",
      "召唤师诅咒的使用次数+1"
    ),
    effect(
      2,
      "定蒙",
      "Centered Spirit",
      "萨达蒙",
      "神女遣霊真訣の継続時間+6秒。領域内フィールド上キャラクターが与える氷元素ダメージの会心ダメージ+15%。",
      "Divine Maiden's Deliverance lasts for 6 seconds longer. Active characters within the skill's field deals 15% increased Cryo CRIT DMG.",
      "Shinjo Shintou的持续时间+6秒。区域内场上角色所造成的冰元素伤害暴击伤害+15%。"
    ),
    effect(
      3,
      "潜虚",
      "Seclusion",
      "阴险",
      "仰霊威召将役呪のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Spring Spirit Summoning by 3.\nMaximum upgrade level is 15.",
      "技能Lv.召唤者诅咒+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "洞観",
      "Insight",
      "洞穴景观",
      "申鶴自身によって「氷翎」効果を付与されたキャラクターが、「氷翎」のダメージアップ効果を発動すると、申鶴は「霜霄訣」を1層獲得する。申鶴が仰霊威召将役呪を発動した時、「霜霄訣」をすべて消費する。消費した層数1につき、その時発動した仰霊威召将役呪のダメージ+5%。この効果は最大50回まで重ね掛け可能、継続時間60秒。",
      "When characters under the effect of Icy Quill applied by Shenhe trigger its DMG Bonus effects, Shenhe will gain a Skyfrost Mantra stack:\n- When Shenhe uses Spring Spirit Summoning, she will consume all stacks of Skyfrost Mantra, increasing the DMG of that Spring Spirit Summoning by 5% for each stack consumed.\n- Max 50 stacks. Stacks last for 60s.",
      "当被新角亲自赋予了“色物”效果的角色激活“色物”伤害增加效果时，新角将获得一层“冰霜薄雾尖”。当真阁发动召唤者诅咒时，所有的“冰霜雾霾”都会被消耗掉。每消耗一层，当时激活的召唤师法术伤害就会增加5%。该效果最多可叠加50次，持续60秒。"
    ),
    effect(
      5,
      "化神",
      "Divine Attainment",
      "加贺美",
      "神女遣霊真訣のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Divine Maiden's Deliverance by 3.\nMaximum upgrade level is 15.",
      "技能Lv.女神传送+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "忘玄",
      "Mystical Abandon",
      "博根",
      "キャラクターが通常攻撃および重撃で「氷翎」効果を発動した時、「氷翎」の発動回数が消費されなくなる。",
      "When characters trigger Icy Quill's effects using Normal and Charged Attack DMG, it does not count toward the Trigger Quota.",
      "当角色普通攻击或重击发动“冰”效果时，不再消耗“冰”发动次数。"
    ),
  ],
};

const entry17: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/366103",
  effects: [
    effect(
      1,
      "霜枯れの墨染櫻",
      "Snowswept Sakura",
      "霜枯墨染樱花",
      "神里綾華の通常攻撃または重撃が敵に氷元素ダメージを与えた時、50%の確率で神里流・氷華のクールタイム-0.3秒、この効果は0.1秒毎に1回のみ発動可能。",
      "When Kamisato Ayaka's Normal or Charged Attacks deal Cryo DMG to opponents, it has a 50% chance of decreasing the CD of Kamisato Art: Hyouka by 0.3s. This effect can occur once every 0.1s.",
      "上里绫香普通攻击或重击对敌人造成冰属性伤害时，有50%概率上里龙冰花冷却时间为-0.3秒，且该效果每0.1秒只能发动一次。"
    ),
    effect(
      2,
      "三重雪関扉",
      "Blizzard Blade Seki no To",
      "三重雪关门",
      "神里流・霜滅発動時、追加で2つの小さい霜見雪関扉を放ち、それぞれ本来の20%分のダメージを与える。",
      "When casting Kamisato Art: Soumetsu, unleashes 2 smaller additional Frostflake Seki no To, each dealing 20% of the original storm's DMG.",
      "上里流/下津激活时，会额外释放2个小型下海雪门，每个造成原始伤害的20%。"
    ),
    effect(
      3,
      "花白錦画紙吹雪",
      "Frostbloom Kamifubuki",
      "花白色锦缎五彩纸屑",
      "神里流・霜滅のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Kamisato Art: Soumetsu by 3.\nMaximum upgrade level is 15.",
      "上里流冰霜破坏技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "栄枯盛衰",
      "Ebb and Flow",
      "上升和下降",
      "神里流・霜滅の霜見雪関扉のダメージを受けた敵の防御力-30%、継続時間6秒。",
      "Opponents damaged by Kamisato Art: Soumetsu's Frostflake Seki no To will have their DEF decreased by 30% for 6s.",
      "受到上里流寂灭的下美雪关道伤害的敌人，防御力降低30%，持续6秒。"
    ),
    effect(
      5,
      "花雲鐘入月",
      "Blossom Cloud Irutsuki",
      "花云钟升月",
      "神里流・氷華のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Kamisato Art: Hyouka by 3.\nMaximum upgrade level is 15.",
      "上里流冰花技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "間水月",
      "Dance of Suigetsu",
      "水月",
      "10秒毎に、神里綾華は「薄氷の舞」状態を獲得し、重撃ダメージが298%アップする。重撃が敵に命中してから0.5秒後、「薄氷の舞」の効果はクリアされ、クールタイムのカウントが開始される。",
      "Kamisato Ayaka gains Usurahi Butou every 10s, increasing her Charged Attack DMG by 298%. This buff will be cleared 0.5s after Ayaka's Charged ATK hits an opponent, after which the timer for this ability will restart.  ",
      "每10秒，上里彩香就会进入“薄冰之舞”状态，使重攻击伤害提高298%。重击击中敌人后0.5秒，“薄冰之舞”效果消失，冷却时间开始计时。"
    ),
  ],
};

const entry18: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/417603",
  effects: [
    effect(
      1,
      "鏡華風姿",
      "Kyouka Fuushi",
      "京花风格的外观",
      "HP50％以下の敵に対して、瞬水剣によるダメージ+40%。",
      "Shunsuiken DMG is increased by 40% against opponents with 50% HP or less.",
      "春水剑对生命值低于50%的敌人造成的伤害+40%。"
    ),
    effect(
      2,
      "世に源泉ありて",
      "World Source",
      "世界上有一个源头",
      "浪閃の重ね掛け上限が5層になる。神里綾人が3層以上の浪閃状態の時、HP上限が50％アップする。",
      "Namisen's maximum stack count is increased to 5. When Kamisato Ayato has at least 3 Namisen stacks, his Max HP is increased by 50%.",
      "Nanisen的堆叠上限为5层。上里绫人等级达到三级以上时，最大生命值增加50%。"
    ),
    effect(
      3,
      "無意弄花",
      "To Admire the Flowers",
      "无意间玩花",
      "神里流・鏡花のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Kamisato Art: Kyouka by 3.\nMaximum upgrade level is 15.",
      "上里流镜花技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "細流厭わず",
      "Endless Flow",
      "我不介意滴滴",
      "神里流・水囿発動後、周囲チーム全員の通常攻撃速度+15%、継続時間15秒。",
      "After using Kamisato Art: Suiyuu, all nearby party members will have 15% increased Normal Attack SPD for 15s.",
      "激活上里流/水漫后，周围所有队员的普通攻击速度+15%，持续15秒。"
    ),
    effect(
      5,
      "万水一露",
      "Bansui Ichiro",
      "10,000 颗水滴",
      "神里流・水囿のスキルLv.+3。最大Lv.15まで。",
      "Increase the Level of Kamisato Art: Suiyuu by 3.\nMaximum upgrade level is 15.",
      "上里流/水本技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "濫觴無底",
      "Boundless Origin",
      "无穷无尽的多样性",
      "神里流・鏡花発動後、神里綾人の次に発動する瞬水剣が敵に命中した時、神里綾人の450%分のダメージを持つ瞬水剣を2回追加で発動する。追加で発動する2回の瞬水剣が浪閃の効果を受けない。",
      "After using Kamisato Art: Kyouka, Ayato's next Shunsuiken attack will create 2 extra Shunsuiken strikes when they hit opponents, each one dealing 450% of Ayato's ATK as DMG. Both these Shunsuiken attacks will not be affected by Namisen.",
      "激活上里流镜花后，当上里绫人的下一个春水剑击中敌人时，会触发相当于上里绫人伤害450%伤害的春水剑两次。额外的两次春水剑激活不受雷仙影响。"
    ),
  ],
};

const entry19: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/358214",
  effects: [
    effect(
      1,
      "絶命の加速",
      "Fatal Acceleration",
      "致命的加速",
      "会心攻撃が発生した5秒間、通常攻撃と重撃の攻撃速度が12%上昇する。5秒毎に一回のみ発動可能。",
      "Upon scoring a CRIT hit, increases ATK SPD of Xinyan's Normal and Charged Attacks by 12% for 5s.\nCan only occur once every 5s.",
      "致命攻击发生后5秒内，普通攻击和重击攻击速度增加12%。每 5 秒只能激活一次。"
    ),
    effect(
      2,
      "オープニング演出",
      "Impromptu Opening",
      "开场表演",
      "反逆の弾きによる物理ダメージの会心率を100%上昇させる。さらに発動する時にLv.3シールド・舞のリズムを生成する。",
      "Riff Revolution Physical DMG has its Crit rate increased by 100%, and will form a shield at Shield Level 3: Rave when cast.",
      "叛军弹跳造成的物理伤害暴击率提高100%。此外，激活后会产生Lv.3护盾/舞蹈节奏。"
    ),
    effect(
      3,
      "摭分の運指",
      "Double Stop",
      "Sukubun 指法",
      "情熱の薙ぎ払いのスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Sweeping Fervor by 3.\nMaximum upgrade level is 15.",
      "热情割草技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "リズムの電線",
      "Wildfire Rhythm",
      "节奏线",
      "情熱の薙ぎ払いの振り回しダメージを受けた敵の物理耐性が15%減少する。継続時間12秒。",
      "Sweeping Fervor's swing DMG decrease opponents Physical RES by 15% for 12s.",
      "受到热情割草挥击伤害的敌人的物理抗性降低 15%。持续时间：12 秒。"
    ),
    effect(
      5,
      "アンコールの叫び",
      "Screaming for Encore",
      "安可哭泣",
      "反逆の弾きのスキルLv.3。最大Lv.15まで。",
      "Increases the Level of Riff Revolution by 3. Maximum upgrade level is 15.",
      "叛乱技能等级3级。最高可达Lv.15。"
    ),
    effect(
      6,
      "地獄のシェーク",
      "Rocking in Flaming",
      "从地狱中摇晃",
      "辛炎の重撃によるスタミナ消費-30%。重撃を発動する時、辛炎の防御力50%分の攻撃力が増加する。",
      "Decrease the stamina consumption of Xinyan Charged Attacks by 30%. Additionally, Xinyan Charged Attack gain an ATK bonus equal to 50% of her DEF.",
      "由于猛烈的火力攻击，体力消耗-30%。发动重击时，攻击力增加真炎防御力的50%。"
    ),
  ],
};

const entry20: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/574166",
  effects: [
    effect(
      1,
      "正絹六通",
      "Six Paths of Sage Silkcraft",
      "真丝六片",
      "羽袖一触の自動制御人形の「たもと」の攻撃範囲+50%。また、チームに千織以外の岩元素キャラクターが存在する場合、羽袖一触の突進終了時、以下の効果を発動する。・「たもと」を追加で1体召喚する。この方法で召喚した千織自身の「たもと」と、岩元素創造物を通して追加召喚した千織自身の「たもと」は同時に最大1体まで存在可能。・固有天賦「錦上添花」の効果を発動する。固有天賦「錦上添花」を解放する必要がある。",
      'The AoE of the automaton doll "Tamoto" summoned by Fluttering Hasode is increased by 50%.\nAdditionally, if there is a Geo party member other than Chiori, Fluttering Hasode will trigger the following after the dash is completed:\nSummon an additional Tamoto. Only one additional Tamoto can exist at the same time, whether summoned by Chiori this way or through the presence of a Geo Construct.\nTriggers the Passive Talent "The Finishing Touch." This effect requires you to first unlock the Passive Talent "The Finishing Touch."',
      "波出一德的自控人偶“田本”的攻击范围+50%。另外，如果队伍中还有千织以外的岩石元素角色，则在波出一德冲锋结束时将激活以下效果。 ・额外召唤一个“田本”。使用这种方法召唤的千织自己的“田本”和通过岩石元素创造额外召唤的千织自己的“田本”一次最多可以存在一个。 ・激活独特天赋“锦城庄”的效果。需要释放独特的天赋“锦城仓”。"
    ),
    effect(
      2,
      "落染五色",
      "In Five Colors Dyed",
      "可拆卸五种颜色",
      "二刀の型・比翼を発動した後の10秒間、3秒毎にフィールド上にいる自身のキャラクターの近くに簡易型自動制御人形の「きぬ」を1体召喚する。「きぬ」は近くの敵に攻撃を仕掛け、「たもと」の170%分に相当する岩元素範囲ダメージを与える。これによるダメージは元素スキルダメージと見なされる。「きぬ」は攻撃を1回行う、または3秒間継続した後に退場する。",
      'For 10s after using Hiyoku: Twin Blades, a simplified automaton doll, "Kinu," will be summoned next to your active character every 3s. Kinu will attack nearby opponents, dealing AoE Geo DMG equivalent to 170% of Tamoto\'s DMG. DMG dealt this way is considered Elemental Skill DMG.\nKinu will leave the field after 1 attack or after lasting 3s.',
      "启动二人型飞行后的 10 秒内，每 3 秒在场上的角色附近召唤一个简单的自动控制人偶“鬼怒”。 “鬼怒”对附近敌人发动攻击，造成“田本”170%的岩石元素伤害。由此造成的伤害被视为元素技能伤害。 “鬼奴”攻击一次或持续3秒后离开。"
    ),
    effect(
      3,
      "綴錦四分",
      "Four Brocade Embellishments",
      "锦涩 笃",
      "羽袖一触のスキルLV.+3。最大Lv.15まで。",
      "Increases the Level of Fluttering Hasode by 3.\nMaximum upgrade level is 15.",
      "初出的技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "衣裁三礼",
      "A Tailor's Three Courtesies",
      "剪衣服仪式",
      "固有天賦「量体裁衣」の後続効果を発動した後の8秒間、フィールド上にいるチーム内自身のキャラクターの通常攻撃、重撃、落下攻撃が近くの敵に命中した時、敵の付近に簡易型自動制御人形の「きぬ」を1体召喚する。この方法で召喚できる「きぬ」は1秒毎に1体のみ。固有天賦「量体裁衣」の当意即妙または裁錦効果の継続期間中、上記方法で召喚できる「きぬ」は最大3体まで。上記効果は15秒毎に1回のみ発動可能。固有天賦「量体裁衣」を解放する必要がある。",
      'For 8s after triggering either follow-up effect of the Passive Talent "Tailor-Made," when your current active character\'s Normal, Charged, or Plunging Attacks hit a nearby opponent, a simplified automaton doll, "Kinu," will be summoned near this opponent. You can summon 1 Kinu every 1s in this way, and up to 3 Kinu may be summoned this way during each instance of "Tailor-Made"\'s Seize the Moment or Tailoring effect. The above effect can be triggered up to once every 15s.\nMust unlock the Passive Talent "Tailor-Made" first.',
      "启动独特天赋“数量衣服”的后续效果后8秒内，当己方角色在场上的普通攻击、重击或坠落攻击击中附近敌人时，敌人附近会召唤一个简易自控人偶“鬼奴”。这样每秒只能召唤一只鬼奴。在独特天赋“全太赛”的土肥特殊名或彩锦效果持续期间，使用上述方法最多可以召唤3只“鬼怒”。上述效果每15秒只能启动一次。需要释放独特天赋“量衣”。"
    ),
    effect(
      5,
      "綾羽二重",
      "Two Silken Plumules",
      "羽田绫",
      "二刀の型・比翼のスキルLV.+3。最大Lv.15まで。",
      "Increases the Level of Hiyoku: Twin Blades by 3.\nMaximum upgrade level is 15.",
      "二剑型飞极技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "万理一空",
      "Sole Principle Pursuit",
      "空万里一",
      "固有天賦「量体裁衣」の後続効果を発動した後、千織自身の羽袖一触のクールタイム-12秒。固有天賦「量体裁衣」を解放する必要がある。また、千織自身の通常攻撃によるダメージは、千織自身の防御力の235%分アップする。",
      'After triggering a follow-up effect of the Passive Talent "Tailor-Made," Chiori\'s own Fluttering Hasode\'s CD is decreased by 12s. Must unlock the Passive "Tailor-Made" first.\nIn addition, the DMG dealt by Chiori\'s own Normal Attacks is increased by an amount equal to 235% of her own DEF.',
      "激活独特天赋“巨衣”的后续效果后，千织自身的波出之触的冷却时间减少12秒。需要释放独特天赋“量衣”。此外，千织自身普通攻击造成的伤害增加千织自身防御力的235%。"
    ),
  ],
};

const entry21: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-14",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/390935",
  effects: [
    effect(
      1,
      "一心二用の術",
      "Multi-Task no Jutsu",
      "一心二代之术",
      "鳴呼流・影貉繚乱のむじむじだるまは、キャラクターのHPを無視し、周囲の敵への攻撃とキャラクターへのHP回復行動を2つを同時に行う。",
      "The Muji-Muji Daruma created by Yoohoo Art: Mujina Flurry will ignore HP limits and can simultaneously attack nearby opponents and heal characters.",
      "明光龙/影见凉兰的无印良品达摩无视角色的生命值，同时执行两个动作：攻击周围的敌人并恢复角色的生命值。"
    ),
    effect(
      2,
      "逃げ道確保",
      "Egress Prep",
      "确保逃生路线",
      "鳴呼流・風隠急進で2つの効果を獲得する。・一回押し時の風々輪・旋舞蹴のダメージ+3.3%。長押しの風々輪状態では、0.5秒毎に風々輪・旋舞蹴のダメージ+3.3%。この方式でアップできる風々輪・旋舞蹴のダメージは66％まで。",
      "Yoohoo Art: Fuuin Dash gains the following effects:\nDMG of Fuufuu Whirlwind Kick in Tapping (mobile)/Press (PC & PlayStation) Mode increased by 3.3%.\nEvery 0.5s in the Fuufuu Windwheel state will increase the DMG of this Fuufuu Whirlwind Kick by 3.3%. The maximum DMG increase possible through this method is 66%.",
      "名光流和风隐急速获得两种效果。 ・按压一次时，风风娃和仙魔姬的伤害+3.3%。如果按住不破娃，不破娃和仙魔鬼的伤害每0.5秒增加3.3%。通过此方法可以增加风风娃和仙武踢的伤害，最高可达66%。"
    ),
    effect(
      3,
      "分身に任せる",
      "Eh, the Bunshin Can Handle It",
      "把它留给你的另一个自我",
      "鳴呼流・影貉繚乱のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Yoohoo Art: Mujina Flurry by 3. Maximum upgrade level is 15.",
      "Meikoryu/暗影环境技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "新しいサボる方法",
      "Skiving: New and Improved",
      "一种新的放松方式",
      "早柚がフィールド上で拡散または星拡散反応を起こした時、元素エネルギーを1.2ポイント回復する。この効果は2秒毎に1回のみ発動可能。",
      "Sayu recovers 1.2 Energy when she triggers a Swirl reaction.\nThis effect occurs once every 2s.",
      "当早宇在场上引起扩散或星扩散反应时，它会恢复1.2点元素能量。该效果每2秒只能发动一次。"
    ),
    effect(
      5,
      "素早さ最優先",
      "Speed Comes First",
      "优先考虑速度",
      "鳴呼流・風隠急進のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Yoohoo Art: Fuuin Dash by 3. Maximum upgrade level is 15.",
      "名光流/风隐 快速进阶技能 Lv. +3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "ぐーたら寝る時間",
      "Sleep O'Clock",
      "是时候去睡觉了",
      "早柚自身の鳴呼流・影貉繚乱によって召喚されたむじむじだるまの攻撃力と回復量は、早柚の元素熟知によって決まる。早柚の元素熟知の数値が1につき、以下の効果を発動する。・むじむじだるまのダメージは攻撃力0.2%分アップする。この方式でアップできるダメージは攻撃力400%分まで。・むじむじだるまによるHP回復量+3。この方式でアップできる回復量は6000まで。",
      "The Muji-Muji Daruma created by Sayu's Yoohoo Art: Mujina Flurry will now also benefit from her Elemental Mastery. Each point of Sayu's Elemental Mastery will produce the following effects:\nIncreases the damage dealt by the Muji-Muji Daruma's attacks by 0.2% ATK. A maximum of 400% ATK can be gained via this method.\nIncreases the HP restored by the Muji-Muji Daruma by 3. A maximum of 6,000 additional HP can be restored in this manner.",
      "由Hayu自己的Meiko Ryu和Kagei Ryoran召唤的Mujimuji Daruma的攻击力和恢复量取决于Hayu对元素的熟悉程度。早游的元素熟练度达到1时，会发动以下效果。 ・无印良品达磨的伤害增加攻击力的0.2%。使用此方法最多可增加攻击力400%的伤害。 ・无印良品达摩的HP恢复量+3。使用此方法最多可增加6000的恢复量。"
    ),
  ],
};

const entry22: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/366289",
  effects: [
    effect(
      1,
      "初番・茂風流羽行",
      "Shoban: Ostentatious Plumage",
      "第一回合：茂风龙右行",
      "児姿優風状態時、放浪者の空居・不生断および空居・風刀界の攻撃速度+10%。また、固有天賦「夢跡一風」により発射された風の矢は追加で攻撃力25%のダメージを与えられる。この効果は固有天賦「夢跡一風」を解放する必要がある。",
      'When in the Windfavored state, the Attack SPD of the Wanderer\'s Kuugo: Fushoudan and Kuugo: Toufukai is increased by 10%.\nAdditionally, the wind arrows fired by the Passive Talent "Gales of Reverie" will deal an additional 25% of his ATK as DMG. You must unlock the Passive Talent "Gales of Reverie" first.',
      "幼稚玉符状态下，云游者的草海/风剑界和草海/风剑世界的攻击速度增加10%。另外，独特天赋“梦痕一风”发射的风箭会额外造成攻击力25%的伤害。此效果需要释放独特天赋“梦之轨迹一风”。"
    ),
    effect(
      2,
      "弐番・箙島廓白浪",
      "Niban: Moonlit Isle Amidst White Waves",
      "第2名：岛岛白浪",
      "児姿優風状態時、空居力の上限値と現在の空居力の差が1あるごとに狂言・式楽伍番の与えるダメージが4%アップする。この方式でアップできる狂言・式楽伍番のダメージは最大200%までとなる。",
      "When in the Windfavored state, Kyougen: Five Ceremonial Plays will see its DMG increased by 4% per point of difference between the max amount of Kuugoryoku Points contrasted with Kuugoryoku's present capacity when using this skill.\nThrough this method, you can increase Kyougen: Five Ceremonial Plays's DMG by a maximum of 200%.",
      "童态由布状态时，狂言/式学五番所造成的伤害，空射力上限与当前空射力每相差1点，造成的伤害增加4%。使用此方法可以增加狂言/式学五番的伤害至200%。"
    ),
    effect(
      3,
      "参番・久世舞夕顔",
      "Sanban: Moonflower Kusemai",
      "三番久世舞尤高",
      "狂言・式楽伍番のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Kyougen: Five Ceremonial Plays by 3.\nMaximum upgrade level is 15.",
      "狂言/式学5级技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "肆番・花月歌浮舟",
      "Yonban: Set Adrift into Spring",
      "美食宴会/花月浮船",
      "羽画・風姿華歌発動時、固有天賦「拾玉得花」で元素タイプと対応する強化効果を得ると、今回の発動で未獲得の強化効果をランダムで1つ獲得する。同時に獲得できる元素タイプと対応する強化効果は最大3種類まで。固有天賦「拾玉得花」を解放する必要がある。",
      'When casting Hanega: Song of the Wind, should the Passive Talent "Jade-Claimed Flower" be triggered, the character will gain buffs in correspondence to the contacted Elemental Type(s), and also obtain a random untriggered buff. A maximum of 3 such corresponding elemental buffs can exist simultaneously.\nYou must unlock the Passive Talent "Jade-Claimed Flower" first.',
      "当Haga/Fushikaka被激活时，如果你获得了与具有独特天赋“Pick-up Tokuhana”的元素类型相对应的强化效果，你将通过该激活随机获得一个未获得的强化效果。最多可同时获得3种元素类型及相应的强化效果。需要释放独特的天赋“射手玉德华”。"
    ),
    effect(
      5,
      "末番・今昔渡来殿",
      "Matsuban: Ancient Illuminator From Abroad",
      "最后一个号码，今昔虎莱电",
      "羽画・風姿華歌のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Hanega: Song of the Wind by 3.\nMaximum upgrade level is 15.",
      "Haga/Fushikaka技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "言祝・霞幕傾松風",
      "Shugen: The Curtains' Melancholic Sway",
      "庆言：霞幕倾松风",
      "児姿優風状態時、放浪者が自ら発動した空居・不生断が敵に命中すると、下記の効果を発動する。／・命中した位置に空居・不生断を追加で1回発動し、本来の40%分のダメージを与える。このダメージは通常攻撃ダメージとみなされる。／・放浪者の空居力が40ポイント未満の時、空居力を4ポイント回復する。この方式による空居力の回復は、0.2秒毎に1回のみ可能。また、1回児姿優風の継続時間中に最大5回まで発動可能。",
      "When the Wanderer actively hits an opponent with Kuugo: Fushoudan while in the Windfavored state, the following effects will occur:\n- Deals an additional instance of Kuugo: Fushoudan at the position hit, dealing 40% of the attack's original DMG. This DMG will be considered Normal Attack DMG.\n- When the Wanderer falls below 40 Kuugoryoku Points, restores 4 Points to him. Kuugoryoku Points can be restored in this manner once every 0.2s. This restoration can occur up to 5 times within one Windfavored duration.",
      "当流浪者的自启动苍镜/风星弹在幼稚的由布状态下击中敌人时，将激活以下效果。 /·在命中位置激活额外的空位/不朽，造成原始伤害的 40%。该伤害被视为普通攻击伤害。 /·当流浪者的自由力量低于40点时，恢复4点自由力量。使用此方法每0.2秒只能恢复一次剩余的能量。此外，在一名孩子出现期间最多可以激活 5 次。"
    ),
  ],
};

const entry23: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-09-08",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352616",
  effects: [
    effect(
      1,
      "四方に沈む魚龍",
      "Sea Beast's Scourge",
      "鱼龙四面沉",
      "雷斫り発動時、HP上限16％相当のシールドを生成し、継続時間15秒。該当シールドは雷ダメージに対して250％の吸収効果がある。",
      "When Stormbreaker is used:\nCreates a shield that absorbs up to 16% of Beidou's Max HP for 15s.\nThis shield absorbs Electro DMG 250% more effectively.",
      "发动雷多里时，产生相当于最大生命值16%的护盾，持续15秒。盾牌对雷击伤害有250%的吸收效果。"
    ),
    effect(
      2,
      "沸き上がる雷",
      "Upon the Turbulent Sea, the Thunder Arises",
      "沸腾的雷霆",
      "雷斫りの稲妻は2体の敵を追加で攻撃可能。",
      "Stormbreaker's arc lightning can jump 2 additional targets.",
      "雷电的闪电可以额外攻击 2 个敌人。"
    ),
    effect(
      3,
      "雷引きの潮",
      "Summoner of Storm",
      "雷潮",
      "浪追いのスキルLv.3（最大Lv.15まで）。",
      "Increases the Level of Tidecaller by 3.\nMaximum upgrade level is 15.",
      "浪追技能 Lv.3（最高 Lv.15）。"
    ),
    effect(
      4,
      "星に導かれた岸線",
      "Stunning Revenge",
      "星星指引的海岸线",
      "攻撃を受けた10秒以内、北斗の通常攻撃は20％の雷ダメージが付与される。",
      "Within 10s of taking DMG, Beidou's Normal Attacks gain 20% additional Electro DMG.",
      "受到攻击后10秒内，北斗的普通攻击会造成20%的闪电伤害。"
    ),
    effect(
      5,
      "白波に映る霞光",
      "Crimson Tidewalker",
      "雾霾反射在白色的波浪上",
      "雷斫りのスキルLv.3（最大Lv.15まで）。",
      "Increase the Level of Stormbreaker by 3.\nMaximum upgrade level is 15.",
      "Raidori技能Lv.3（最高Lv.15）。"
    ),
    effect(
      6,
      "北斗の祓い",
      "Bane of Evil",
      "北极星的驱魔",
      "雷斫り継続中、周囲の敵の雷耐性-15％。輝映・星電導：雷斫り継続期間中、近くの敵の氷元素耐性-15%、現在のフィールド上キャラクターの元素熟知+200。",
      "During the duration of Stormbreaker, the Electro RES of surrounding enemies is decreased by 15%.",
      "当雷霆持续时，周围敌人的雷电抗性为-15%。光明反射/星导：雷暴持续期间，附近敌人冰元素抗性-15%，场上当前角色元素熟悉度+200。"
    ),
  ],
};

const entry24: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-09-08",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/662778",
  effects: [
    effect(
      1,
      "瑞枝さす",
      "Sasu Mizue",
      "水江佐须",
      "夢見月瑞希が夢浮かみ状態にある時、3.5秒毎に近くの敵に3秒継続する「二十三夜待ち」効果を与える。二十三夜待ち効果の影響を受けている敵が風元素ダメージを受け、拡散または星拡散反応を起こした時、該当効果は解除され、その反応によるダメージはそれぞれ、夢見月瑞希の元素熟知の1100%/550%分アップする。この時、その敵に対して追加で1回攻撃し、夢見月瑞希の元素熟知の1000%分の風元素ダメージを与える。輝映・星拡散：上述の追加ダメージは夢見月瑞希の元素熟知の400%分の風元素ダメージへと変わる。このダメージは星拡散反応によるダメージとみなされる。",
      "When Mizuki Yumezuki is in a dream state, every 3.5 seconds she inflicts a \"wait for 23 nights\" effect on nearby enemies that lasts for 3 seconds. When an enemy affected by the 23-night wait effect receives wind elemental damage and causes a diffusion or star diffusion reaction, the effect will be canceled and the damage caused by that reaction will be increased by 1100%/550% of Yumezuki Mizuki's elemental mastery, respectively. At this time, attack that enemy one more time and deal wind elemental damage equal to 1000% of Mizuki Yumezuki's elemental mastery. Radiance/Star Diffusion: The additional damage mentioned above changes to wind elemental damage equal to 400% of Mizuki Yumezuki's elemental mastery. This damage is considered damage due to star diffusion reactions.",
      "当梦月水希处于梦境状态时，每3.5秒她会对附近的敌人造成“等待23夜”的效果，持续3秒。当受到23夜等待效果影响的敌人受到风元素伤害并引起扩散或星扩散反应时，该效果将被取消，该反应造成的伤害将分别增加梦月水树元素掌握度的1100%/550%。此时，再攻击该敌人一次，造成梦月水希元素掌握力1000%的风属性伤害。光辉/星辰扩散：上述额外伤害变为风元素伤害，相当于梦月水希元素掌握力的400%。这种损坏被认为是由于星体扩散反应造成的损坏。"
    ),
    effect(
      2,
      "希なる朝の",
      "rare morning",
      "难得的早晨",
      "夢浮かみ状態に入る時、夢見月瑞希の元素熟知1ごとに、周囲のチーム全員（夢見月瑞希を除く）の炎元素、水元素、氷元素、雷元素ダメージ+0.04%。この効果は夢浮かみ状態終了まで継続する。また、夢見月瑞希が夢浮かみ状態の時、周囲の敵の炎元素耐性、水元素耐性、氷元素耐性、雷元素耐性および風元素耐性-20%。",
      "When entering the dream state, for every 1 of Mizuki Yumemizuki's elemental proficiency, the fire elemental, water elemental, ice elemental, and lightning elemental damage of all surrounding team members (excluding Mizuki Yumemizuki) increases by 0.04%. This effect lasts until the dream state ends. Also, when Mizuki Yumezuki is in a dream state, the fire elemental resistance, water elemental resistance, ice elemental resistance, thunder elemental resistance, and wind elemental resistance of surrounding enemies will be reduced by 20%.",
      "进入梦境状态时，梦水美月的元素熟练度每增加1，周围所有队员（梦水美月除外）的火元素、水元素、冰元素、雷元素伤害增加0.04%。这种效果会持续到梦境结束。另外，梦月水希处于梦境状态时，周围敌人的火元素抗性、水元素抗性、冰元素抗性、雷元素抗性、风元素抗性都会降低20%。"
    ),
    effect(
      3,
      "なみだ月",
      "Namida moon",
      "纳米达月亮",
      "元素スキル秋沙歌枕巡りのスキルLV.+3。最大Lv.15まで。",
      "Elemental skill Akisa song pillow tour skill LV.+3. Up to maximum Lv.15.",
      "元素技能秋纱歌枕游技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "夢見草",
      "dream grass",
      "梦草",
      "元素爆発極楽秘湯療法の夢見風の名菓を拾ったとき、ダメージを与えると同時にHPを回復し、かつチーム内で付近にいるHPが低い別のキャラクター1名のHPを追加で回復する。HP回復量は夢見月瑞希の元素熟知の266%に相当し、さらに夢見月瑞希の元素エネルギーを5回復する。1回の極楽秘湯療法継続期間中、この方法による元素エネルギーの回復は最大4回まで。",
      "When you pick up the Elemental Explosion Paradise Secret Hot Spring Remedy's dream-like confectionery, it deals damage and recovers HP at the same time, and additionally recovers the HP of another nearby character on your team who has low HP. The amount of HP recovered is equivalent to 266% of Mizuki Yumemizuki's elemental mastery, and also recovers 5 elemental energy for Mizuki Yumemizuki. Elemental energy can be recovered up to 4 times using this method during the duration of one Gokuraku Hitsuyu treatment period.",
      "当你拾取元素爆乐园秘温泉灵药的梦幻糖果时，它会在造成伤害的同时恢复生命值，并额外恢复我方队伍中其他生命值较低的角色的生命值。恢复的生命值相当于梦水希的元素掌握力的266%，同时还为梦水希恢复5点元素能量。使用此方法，在一个极乐日汤治疗周期内，元素能量最多可恢复 4 次。"
    ),
    effect(
      5,
      "恋ふる夜空に",
      "In the night sky full of love",
      "在充满爱的夜空",
      "元素爆発極楽秘湯療法のスキルLV.+3。最大Lv.15まで。",
      "Elemental Explosion Paradise Secret Hot Spring Therapy skill LV.+3. Up to maximum Lv.15.",
      "元爆乐园秘温泉疗愈技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "煙る月",
      "smoking moon",
      "冒烟的月亮",
      "夢見月瑞希が夢浮かみ状態にある時、付近にいるチーム内キャラクターの与える拡散反応ダメージに会心が発生する。なお会心率は30%、会心ダメージは100%に固定される。さらに、これらのキャラクターの与える星拡散反応ダメージの会心率+10%、会心ダメージ+20%。夢見月瑞希の元素熟知が500を超えた場合、その超えた分の元素熟知1につき、夢見月瑞希の会心率+0.04%、会心ダメージ+0.16%。この方法によって夢見月瑞希の会心率は最大20%、会心ダメージは最大80%までアップできる。",
      "When Mizuki Yumezuki is in a dream state, she will be triggered by diffusion reaction damage from nearby characters on her team. The critical hit rate is fixed at 30% and the critical damage is fixed at 100%. In addition, the critical rate of star diffusion reaction damage dealt by these characters +10% and critical damage +20%. If Mizuki Yumemizuki's elemental proficiency exceeds 500, Mizuki Yumemizuki's critical rate +0.04% and critical damage +0.16% for each elemental proficiency exceeded. With this method, Mizuki Yumezuki's critical hit rate can be increased by up to 20%, and her critical damage can be increased by up to 80%.",
      "当梦月水树处于梦境状态时，她会受到附近团队角色的扩散反应伤害而触发。暴击率固定为30%，暴击伤害固定为100%。此外，这些角色造成的星辰扩散反应伤害暴击率+10%，暴击伤害+20%。梦水美月的元素熟练度超过500时，每超过1个元素熟练度，梦水美月的暴击率+0.04%，暴击伤害+0.16%。通过这个方法，梦月水希的暴击率最多可以增加20%，暴击伤害最多可以增加80%。"
    ),
  ],
};

const entry25: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/655054",
  effects: [
    effect(
      1,
      "「雲の合間にかの人あり」",
      '"There\'s that person between the clouds."',
      "“云间有那个人。”",
      "元素スキル鳳跡随翦舞を発動し、固有天賦「四方封刀の霊占」の元素変化を起こした後、藍硯が敵に向かって翦月輪を投げる時、追加で翦月輪を1つ投げ出す。固有天賦「四方封刀の霊占」を解放する必要がある。",
      "After activating the elemental skill Houji Zuikumai and causing the elemental change of the unique talent ``Spiritual Divination of Four Directional Sealed Swords'', when Aiken throws a Hatgetsu Ring at the enemy, he will also throw out one Hat Moon Ring. It is necessary to unlock the unique talent ``Spiritual fortune-telling of the Four Directions Sealed Swords''.",
      "激活元素技能后嗣醉苦舞并引发独特天赋“四向封剑灵占”的元素变化后，艾肯向敌人投掷八月环时，也会同时投掷出一枚帽月环。需要解锁独特天赋“四方封剑灵算”。"
    ),
    effect(
      2,
      "「舞う袂軽く美玉光る」",
      "``The dancing sleeves are lightly sparkling.''",
      "“舞动的袖子闪闪发光。”",
      "鳳跡シールド期間中、フィールド上にいるチーム内の自身のキャラクターの通常攻撃がダメージを与えた時、鳳跡シールドのダメージ吸収量を40%回復する。最大、シールド創造時のダメージ吸収量まで回復する。この効果は2秒毎に1回のみ発動可能。",
      "During the Otori Ato Shield period, when your character's normal attack on the field inflicts damage, the Otori Ato Shield's damage absorption amount will be restored by 40%. Recovers up to the amount of damage absorbed at the time of shield creation. This effect can only be activated once every 2 seconds.",
      "鸟之盾期间，当你的角色在场上普通攻击造成伤害时，鸟之盾的伤害吸收量将恢复40%。恢复最多为护盾创建时吸收的伤害量。该效果每2秒只能发动一次。"
    ),
    effect(
      3,
      "「白鳳に乗りて霧を裂く」",
      '"Ride the white phoenix and split the fog"',
      "“骑白凤凰，劈迷雾”",
      "元素スキル鳳跡随翦舞のスキルLV.+3。最大Lv.15まで。",
      "Elemental skill Otorizuizamai's skill LV. +3. Up to maximum Lv.15.",
      "元素技能大鸟瑞泽舞的技能LV。 +3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "「龍鷹集いて血珠を成す」",
      '"The Dragonhawks gather to form a Blood Pearl."',
      "“龙鹰聚集，形成血珠。”",
      "元素爆発月踏む鶴弦を発動後の12秒間、周囲チーム全員の元素熟知+60。",
      "For 12 seconds after activating Elemental Explosion Tsurugen Tsurugen, all surrounding team members' elemental proficiency +60.",
      "元素爆弹鹤元发动后12秒内，周围所有队员的元素熟练度+60。"
    ),
    effect(
      5,
      "「一別相逢ひて胸高鳴る」",
      "``I'm excited to meet Ichibetsu''",
      "“我很高兴见到一别”",
      "元素爆発月踏む鶴弦のスキルLV.+3。最大Lv.15まで。",
      "Elemental Explosion Moon Stepping Tsurugen's skill LV.+3. Up to maximum Lv.15.",
      "元素爆月踏鹤元的技能LV.+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "「風に乗る銀鸞の声」",
      '"Ginran\'s voice riding on the wind"',
      "“银兰的声音随风飘扬”",
      "鳳跡随翦舞の使用可能回数+1。",
      "Increases the number of times you can use Hou Ato Zuikamai by 1.",
      "使你可以使用的次数增加 1 次。"
    ),
  ],
};

const entry26: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/521833",
  effects: [
    effect(
      1,
      "器物流転",
      "Material Circulation",
      "设备转移",
      "秘法・サプライズ特別配送を発動した時、綺良々のHP上限8000毎にニャンダモンを追加で1個生成する。この方法で生成されるニャンダモンは最大4個まで。",
      "Every 8,000 Max HP Kirara possesses will cause her to create 1 extra Cat Grass Cardamom when she uses Secret Art: Surprise Dispatch. A maximum of 4 extra can be created this way.",
      "发动秘术/惊喜特快专递时，基拉每有 8000 点生命值，就会额外生成 1 个尼安达兽。使用此方法最多可以生成 4 个 Nyandamon。"
    ),
    effect(
      2,
      "八隅・完璧梱包術",
      "Perfectly Packaged",
      "八角/完美包装工艺",
      "にゃんにゃん町飛脚のネコ箱急便状態にある綺良々は、接触したチーム内他のキャラクターに安全運送シールド・重要貨物状態に与える。安全運送シールド・重要貨物のダメージ吸収量はにゃんにゃん町飛脚の安全運送シールド吸収量上限の40%に相当し、草元素ダメージに対して250%の吸収効果がある。安全運送シールド・重要貨物状態は12秒継続し、キャラクター1体につき、10秒毎に最大1回発動可能。",
      "When Kirara is in the Urgent Neko Parcel state of Meow-teor Kick, she will grant other party members she crashes into Critical Transport Shields.\nThe DMG absorption of Critical Transport Shield is 40% of the maximum absorption Meow-teor Kick's normal Shields of Safe Transport are capable of, and will absorb Dendro DMG with 250% effectiveness.\nCritical Transport Shields last 12s and can be triggered once on each character every 10s.",
      "处于 Nyan Nyan 镇 Hikyaku 的 Nekobako Express 状态的 Kirara 给团队中接触安全运输盾/重要货物状态的其他角色提供了帮助。安全运输护盾/重要货物的伤害吸收量相当于喵喵镇飞脚安全运输护盾吸收量上限的40%，对草元素伤害有250%的吸收效果。安全运输护盾/重要货物状态持续 12 秒，每个角色最多每 10 秒激活一次。"
    ),
    effect(
      3,
      "万戸門札に通ず",
      "Universal Recognition",
      "通向万都梦萨",
      "にゃんにゃん町飛脚のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Meow-teor Kick by 3.\nMaximum upgrade level is 15.",
      "喵喵镇飞脚技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "韋駄天駿足",
      "Steed of Skanda",
      "伊达天润作",
      "安全運送シールド、または安全運送シールド・重要貨物状態のフィールド上キャラクターの通常攻撃、重撃、または落下攻撃が敵に命中した後、綺良々はニャンダモン・ミニを使って連携攻撃を行い、綺良々の攻撃力200％分の草元素ダメージを与える。このダメージは元素爆発ダメージと見なされる。この効果は3.8秒毎に最大1回のみ発動可能で、チーム全員がクールタイムを共有する。",
      "After active character(s) protected by Shields of Safe Transport or Critical Transport Shields hit opponents with Normal, Charged, or Plunging Attacks, Kirara will perform a coordinated attack with them using Small Cat Grass Cardamoms, dealing 200% of her ATK as Dendro DMG. DMG dealt this way is considered Elemental Burst DMG. This effect can be triggered once every 3.8s. This CD is shared between all party members.",
      "场上处于安全运输护盾、安全运输护盾/重要货物状态的角色进行普通攻击、重击或坠落攻击命中敌人后，基拉亚会使用尼安达蒙迷你进行连动攻击，造成基拉亚攻击力200%的草元素伤害。这种伤害被视为元素爆炸伤害。该效果每3.8秒只能激活一次，冷却时间由全队成员共享。"
    ),
    effect(
      5,
      "一日千里",
      "A Thousand Miles in a Day",
      "每天 1,000 英里",
      "秘法・サプライズ特別配送のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Secret Art: Surprise Dispatch by 3.\nMaximum upgrade level is 15.",
      "秘密/惊喜特快专递技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "道中百景心得たり",
      "Countless Sights to See",
      "一路上我了解到了大约100个观点。",
      "綺良々が元素スキルまたは元素爆発を発動した後15秒間、周囲のチーム全員の全元素ダメージ+12%。",
      "All nearby party members will gain 12% All Elemental DMG Bonus within 15s after Kirara uses her Elemental Skill or Burst.",
      "琪拉拉发动元素技能或元素爆炸后15秒内，周围所有队员的所有元素伤害+12%。"
    ),
  ],
};

const entry27: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352615",
  effects: [
    effect(
      1,
      "壊却・三界破壊",
      "Dissolution Eon - Destroyer of Worlds",
      "毁灭/三界毁灭",
      "風輪両立の使用可能回数+1。",
      "Increases Lemniscatic Wind Cycling's charges by 1.",
      "增加风戒和风戒同时使用的次数。"
    ),
    effect(
      2,
      "空却・虚空開敷の変",
      "Annihilation Eon - Blossom of Kaleidos",
      "排空和排空事件",
      "フィールド上にいない時、魈自身の元素チャージ効率+25%。",
      "When in party but not the currently active character, Xiao's Energy Recharge is increased by 25%.",
      "不在场时，梅的元素充能效率+25%。"
    ),
    effect(
      3,
      "降魔・憤怒の相",
      "Evil Conqueror - Wrath Deity",
      "爆发/愤怒之面",
      "風輪両立のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Lemniscatic Wind Cycling by 3.\nMaximum upgrade level is 15.",
      "技能Lv.两个风环+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "神通・諸苦滅尽",
      "Transcension - Extinction of Suffering",
      "神圣的智慧和所有的痛苦",
      "魈のHPが50%未満の時、防御力+100%。",
      "When Xiao's HP falls below 50%, gains a 100% DEF Bonus.",
      "当凯的生命值低于50%时，防御力+100%。"
    ),
    effect(
      5,
      "成却・無明増長",
      "Evolution Eon - Origin of Ignorance",
      "成功和无知都会增加",
      "靖妖儺舞のスキルLv.+3。最大Lv.15まで。",
      "Increase the Level of Bane of All Evil by 3.\nMaximum upgrade level is 15.",
      "亚苏娜·麦技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "降魔・護法夜叉",
      "Evil Conqueror - Vigilant Yaksha",
      "恶魔/夜叉悟空",
      "靖妖儺舞状態の時、落下攻撃が2体以上の敵に命中すると、風輪両立の使用回数+1。その後の1秒間以内は、クールタイム関係なく風輪両立を発動できる。",
      "During Bane of All Evil, hitting 2 or more enemies with a Charged Attack grants Lemniscatic Wind Cycling 1 additional charge and reduces Lemniscatic Wind Cycling's CD by 1s.",
      "耶苏那布状态下，如果坠落攻击击中两个或两个以上敌人，风环使用次数增加1次。接下来的1秒内，无论冷却时间如何，都可以激活风环兼容。"
    ),
  ],
};

const entry28: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352598",
  effects: [
    effect(
      1,
      "回転する怒風",
      "Raging Vortex",
      "旋转的愤怒的风",
      "旋風の剣は周囲5メートル以内の敵をゆっくりと自分の前に吸い寄せることができる。",
      "Decreases the CD of Foul Legacy: Raging Tide by 20%.",
      "旋风剑可以缓慢地将5米内的敌人吸引向你。"
    ),
    effect(
      2,
      "革新の旋風",
      "Uprising Whirlwind",
      "创新旋风",
      "元素エネルギー回復効率+16%。",
      "Increases Energy Recharge by 16%.",
      "元素能量回收效率+16%。"
    ),
    effect(
      3,
      "天地の剛風",
      "Sweeping Gust",
      "天地强风",
      "激風の息のスキルLv.+3（最大Lv.15まで）。",
      "Increases the level of Gust Surge by 3.\nMaximum upgrade level is 15.",
      "狂风吐息技能Lv. +3（最高可达 Lv.15）。"
    ),
    effect(
      4,
      "恩眷の和風",
      "Cherishing Breezes",
      "日本式的仁慈",
      "旋風の剣継続中、自身の受けるダメージ-10%。",
      "Reduces DMG taken while casting Palm Vortex by 10%.",
      "当旋风剑继续时，受到的伤害-10%。"
    ),
    effect(
      5,
      "群星の渦風",
      "Vortex Stellaris",
      "星团旋风",
      "旋風の剣のスキルLv.+3（最大Lv.15まで）。",
      "Increases the level of Palm Vortex by 3.\nMaximum upgrade level is 15.",
      "旋风剑技Lv. +3（最高可达 Lv.15）。"
    ),
    effect(
      6,
      "もつれる信風",
      "Intertwined Winds",
      "纠结的真福",
      "激風の息によるダメージを受けた目標の風耐性−20%。元素変化があった場合、該当の元素耐性-20%。",
      "Targets who take DMG from Gust Surge have their Anemo RES decreased by 20%.\nIf an Elemental Absorption occurred, then their RES towards the corresponding Element is also decreased by 20%.",
      "-20% 受猛烈风息伤害的目标的风抗性。如果有元素变化，则相应的元素抗性-20%。"
    ),
  ],
};

const entry29: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/352670",
  effects: [
    effect(
      1,
      "巍然たる青岩",
      "Invincible Stonewall",
      "令人惊叹的蓝色岩石",
      "味方が岩潮幾重岩の山に包囲される時、会心率+10%、中断耐性がアップする。",
      "Party members within the radius of Wake of Earth have their CRIT Rate increased by 10% and have increased resistance against interruption.",
      "当友军被石尾一重岩山包围时，暴击率+10%，中断抗性增加。"
    ),
    effect(
      2,
      "不穏な溶岩",
      "Rockcore Meltdown",
      "令人不安的熔岩",
      "星落としの剣の荒星が破壊される時爆破が再び発生し、周囲の敵に星落としの剣のダメージ相当の岩範囲ダメージを与える。",
      "When the meteorite created by Starfell Sword is destroyed, it will also explode, dealing additional AoE Geo DMG equal to the amount of damage dealt by Starfell Sword.",
      "当落星剑的粗星被摧毁时，再次发生爆炸，对周围敌人造成等同于落星剑伤害的岩石区域伤害。"
    ),
    effect(
      3,
      "八方の岩",
      "Will of the Rock",
      "八方之岩",
      "岩潮幾重のスキルLv.+3。最大Lv.15まで。",
      "Increases the level of Wake of Earth by 3.\nMaximum upgrade level is 15.",
      "岩石育江的技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "険しい重岩",
      "Reaction Force",
      "陡峭的重岩",
      "岩潮幾重が引き起こす振動波が敵に命中する度、元素エネルギーが5回復する。この方法で1回で最大25まで回復可能。",
      "The shockwave triggered by Wake of Earth regenerates 5 Energy for every enemy hit. A maximum of 25 Energy can be recovered in this manner.",
      "岩生育江产生的振动波每击中敌人一次，就会恢复5点元素能量。使用此方法最多可以一次性恢复25点。"
    ),
    effect(
      5,
      "天墜の岩",
      "Meteorite Impact",
      "天上的岩石",
      "星落としの剣のスキルLv.+3。最大Lv.15まで。",
      "Increases the level of Starfell Sword by 3.\nMaximum upgrade level is 15.",
      "星落剑技等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "永世の磐岩",
      "Everlasting Boulder",
      "永恒之石",
      "岩潮幾重の岩の山の継続時間+5秒、星落としの剣荒星の継続時間+10",
      "The barrier created by Wake of Earth lasts 5s longer. The meteorite created by Starfell Sword lasts 10s longer.",
      "岩潮多岩山持续时间+5秒，星落剑荒灰持续时间+10"
    ),
  ],
};

const entry30: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/395530",
  effects: [
    effect(
      1,
      "豊穣の春雷",
      "Spring Thunder of Fertility",
      "收获春雷",
      "雷影剣発動時に生成する豊穣の勾玉の数を3つにアップ。",
      "The number of Abundance Amulets that can be generated using Lightning Blade is increased to 3.",
      "雷影剑发动时生成的生育勾玉数量增加至3个。"
    ),
    effect(
      2,
      "激怒の蒼雷",
      "Violet Vehemence",
      "愤怒的蓝雷",
      "電光雷轟の威光の落雷が敵に命中すると、敵の雷元素耐性-15%、継続時間8秒。",
      "When Falling Thunder created by Bellowing Thunder hits an opponent, it will decrease their Electro RES by 15% for 8s.",
      "雷霆之威的雷电击中敌人时，降低敌人15%的雷元素抗性，持续8秒。"
    ),
    effect(
      3,
      "連延の遠雷",
      "Distant Crackling",
      "远处连续不断的雷声",
      "電光雷轟のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Bellowing Thunder by 3. Maximum upgrade level is 15.",
      "闪电技能 Lv. +3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "予測不能な雷雲",
      "Fickle Cloudstrike",
      "不可预测的雷雨云",
      "キャラクターが雷影剣で生成した豊穣の勾玉を獲得した時、該当キャラクターの元素エネルギーが35%未満の場合、豊穣の勾玉で回復できる元素エネルギー+100%。",
      "When a character obtains Abundance Amulets generated by Lightning Blade, if this character's Energy is less than 35%, the Energy restored by the Abundance Amulets is increased by 100%.",
      "当角色获得雷影剑生成的丰饶勾玉时，如果角色的元素能量低于35%，丰饶勾玉所能恢复的元素能量将会增加100%。"
    ),
    effect(
      5,
      "荒野の雷鳴",
      "Clamor in the Wilds",
      "旷野中的雷声",
      "雷影剣のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Lightning Blade by 3. Maximum upgrade level is 15.",
      "雷影剑技等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "世を揺るがす神雷",
      "World-Shaker",
      "震撼天地的神雷",
      "電光雷轟が威光の落雷を2回引き起こすたびに、次回の威光の落雷のダメージ+100%。さらに現在のキャラクターの元素エネルギーを1ポイント回復する。",
      "Every 2 Falling Thunder attacks triggered by Bellowing Thunder will increase the DMG dealt by the next Falling Thunder by 200%, and will restore an additional 1 Energy to the current character.",
      "闪电每造成两次威望雷击，下一次威望雷击的伤害就会增加100%。此外，还为当前角色恢复1点元素能量。"
    ),
  ],
};

const entry31: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-28",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/466495",
  effects: [
    effect(
      1,
      "寄身の倚草",
      "Parasitic Creeper",
      "吉草",
      "草緑剣が敵に命中すると、旅人の元素エネルギーが3.5回復する。",
      "After Razorgrass Blade hits an opponent, it will regenerate 3.5 Energy for the Traveler.",
      "草青剑击中敌人时，旅者的元素能量恢复3.5点。"
    ),
    effect(
      2,
      "壮健なる勁草",
      "Green Resilience",
      "强壮健康的草",
      "草蓮灯の存在時間+3秒。",
      "Lea Lotus Lamp's duration is increased by 3s.",
      "索兰托的存在时间+3秒。"
    ),
    effect(
      3,
      "婆娑の瑶草",
      "Whirling Weeds",
      "奶奶的艾索",
      "草緑剣のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Razorgrass Blade by 3.\nMaximum upgrade level is 15.",
      "草绿色剑技等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "甘露の蜜草",
      "Treacle Grass",
      "蜜露花蜜",
      "草蓮灯が蓮光幻変を発動すると、固有天賦「蔓生の埜草」の「蓮光遍照」効果を5層獲得する。固有天賦「蔓生の埜草」を解放する必要がある。",
      'After the Lea Lotus Lamp triggers a Lotuslight Transfiguration, it will obtain 5 stacks of the Overflowing Lotuslight effect from the Passive Talent "Verdant Overgrowth."\nYou must have unlocked this Passive Talent first.',
      "当索兰托激活砖石幻象时，它会获得5层独特天赋“藤蔓草”的“砖石变书”效果。需要释放独特天赋“藤蔓草”。"
    ),
    effect(
      5,
      "迅生の豊草",
      "Viridian Transience",
      "大量快速生长的植物",
      "臥草若化のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Surgent Manifestation by 3.\nMaximum upgrade level is 15.",
      "加古萨·杨的技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "蘊思の霜草",
      "Withering Aggregation",
      "霜草",
      "草蓮灯の「蓮光遍照」効果を受けたキャラクターによる草元素ダメージ+12%。草蓮灯が蓮光幻変を発動している場合、さらに対応する元素ダメージ+12%",
      "The Dendro DMG Bonus of the character under the effect of Overflowing Lotuslight as created by the Lea Lotus Lamp is increased by 12%. If the Lamp has experienced a Lotuslight Transfiguration previously, the character will also gain 12% DMG Bonus for the corresponding element.",
      "受到索兰托“恋子变奏”效果影响的角色，草元素伤害+12%。如果索兰托激活砖块源变，相应的元素伤害+12%"
    ),
  ],
};

const entry32: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/544186",
  effects: [
    effect(
      1,
      "細波の湖水",
      "Swelling Lake",
      "湖水细波",
      "源水の雫を拾うと、旅人は元素エネルギーを2ポイント回復する。固有天賦「無染の清水」を解放する必要がある。",
      'Picking up a Sourcewater Droplet will restore 2 Energy to the Traveler.\nRequires the Passive Talent "Spotless Waters."',
      "拾取源水滴可为旅行者恢复 2 点元素能量。需要释放独特天赋“不染纯净水”。"
    ),
    effect(
      2,
      "潺湲の碧水",
      "Trickling Purity",
      "七竹的碧水",
      "昇流統水の浮遊水沫の移動速度-30%、継続時間+3秒。",
      "The Movement SPD of Rising Waters' bubble will be decreased by 30%, and its duration increased by 3s.",
      "升水的漂浮水滴移动速度-30%，持续时间+3秒。"
    ),
    effect(
      3,
      "荒天の波水",
      "Turbulent Ripples",
      "暴风雨天气的波浪",
      "水紋の剣のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Aquacrest Saber by 3.\nMaximum upgrade level is 15.",
      "水印剑技等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "傾落の流水",
      "Pouring Descent",
      "落水",
      "水紋の剣を発動する時、ダメージ吸収量がHP上限の10%に値する水紋シールドを生成する。このシールドは水元素ダメージに対して 250%の吸収効果があり、発動完了まで持続する。2秒毎に1回、露雫が敵に命中した後、旅人が水紋シールド状態にある場合、水紋シールドのダメージ吸収量を旅人のHP上限の10%まで補充する。旅人が水紋シールド状態でない場合、水紋シールドを再生成する。",
      "When using Aquacrest Saber, an Aquacrest Aegis that can absorb 10% of the Traveler's Max HP in DMG will be created and will absorb Hydro DMG with 250% effectiveness. It will persist until the Traveler finishes using the skill.\nOnce every 2s, after a Dewdrop hits an opponent, if the Traveler is being protected by Aquacrest Aegis, the DMG Absorption of the Aegis will be restored to 10% of the Traveler's Max HP. If the Traveler is not presently being protected by an Aegis, one will be redeployed.",
      "激活水波纹剑时，会产生一个水波纹护盾，吸收最大生命值10%的伤害。该护盾吸收 250% 的水元素伤害并持续到激活完成。每2秒一次，露珠击中敌人后，若旅者处于水印护盾状态，则补充水印护盾的伤害吸收量至旅者最大生命值的10%。如果旅行者没有水印盾，则重新生成水印盾。"
    ),
    effect(
      5,
      "回旋の曲水",
      "Churning Whirlpool",
      "旋转的水",
      "昇流統水のスキルLv.+3。最大Lv.15まで。",
      "Increases the Level of Rising Waters by 3.\nMaximum upgrade level is 15.",
      "升水指挥技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "正義の潮水",
      "Tides of Justice",
      "正义之潮",
      "旅人が源水の雫を拾う時、追加で周囲にいるHP割合の最も低いチーム内のキャラクターのHPを回復する。回復量はそのキャラクターのHP上限の6%に相当する。",
      "When the Traveler picks up a Sourcewater Droplet, they will restore HP to a nearby party member with the lowest remaining HP percentage based on 6% of said member's Max HP.",
      "当旅行者拾取一滴源水时，他会额外恢复附近队伍中生命百分比最低的角色的生命值。恢复量相当于角色最大生命值的6%。"
    ),
  ],
};

const entry33: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-08-13",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/629612",
  effects: [
    effect(
      1,
      "流光の星火",
      "streaming starfire",
      "流星火",
      "「グーシィ・トース」が化けた「蝕まれし源焔の主」と戦う時・ブレイジング・ロックまたはバーニング・ロックが存在する間、旅人の攻撃力+40%、受けるダメージ-40%。また、中断耐性がアップする。【源火の玉座に奉納後】ブレイジング・ロックまたはバーニング・ロックが存在する間、フィールド上キャラクターの与えるダメージ+6%。フィールド上キャラクターが夜魂の加護状態にある場合、与えるダメージがさらに+9%。",
      'When "Goosey Toth" fights the transformed "Lord of the Corrupted Flames" - While Blazing Rock or Burning Rock is present, the traveler\'s attack power +40% and damage received -40%. It also increases interruption resistance. [After offering to the Throne of Source Fire] While Blazing Rock or Burning Rock exists, damage dealt by characters on the field increases by 6%. If a character on the field is under the protection of night spirits, the damage dealt will be increased by an additional 9%.',
      "当“古西托斯”与变形后的“腐化火焰之王”战斗时 - 当炽热岩石或燃烧岩石存在时，旅行者的攻击力+40%，受到的伤害-40%。它还增加了抗中断能力。 [献祭源火王座后]当炽热岩石或燃烧岩石存在时，场上角色造成的伤害增加6%。场上角色受到夜灵保护时，造成的伤害额外增加9%。"
    ),
    effect(
      2,
      "常明の燭火",
      "Evergreen candle",
      "常青蜡烛",
      "「グーシィ・トース」が化けた「蝕まれし源焔の主」と戦う時、夜魂の加護状態にある場合、旅人の元素タイプが炎元素の攻撃が敵に命中した後、該当敵の炎元素耐性-20%、継続時間6秒。この効果は最大2層まで重ね掛けでき、継続時間は層ごとに独立してカウントされる。【源火の玉座に奉納後】元素スキル流火の剣発動後の12秒間、付近にいるチーム内キャラクターが敵に炎元素関連反応を起こした後、旅人は夜魂値を14回復する。元素スキル流火の剣を発動するたびに、この方法で夜魂値を最大28回復可能。",
      "When fighting the transformed \"Lord of the Corrupted Flames\", if the traveler is under the protection of the night spirit, after the traveler's elemental type fire elemental attack hits the enemy, the enemy's fire elemental resistance -20%, duration: 6 seconds. This effect can be stacked up to two layers, and the duration is counted independently for each layer. [After offering to the Throne of Source Fire] For 12 seconds after activating the elemental skill Sword of Flowing Fire, the traveler will recover 14 night soul values ​​after a nearby character on the team causes a flame element-related reaction to the enemy. Every time you activate the elemental skill Sword of Flowing Fire, you can recover up to 28 night soul values ​​in this way.",
      "与变身的“腐化烈焰领主”战斗时，如果旅者受到夜灵的保护，旅者的元素系火元素攻击击中敌人后，敌人的火元素抗性-20%，持续时间：6秒。该效果最多可以叠加两层，并且每层的持续时间是独立计算的。 【献祭源火王座后】激活元素技能流火剑后12秒内，附近队伍中的角色对敌人造成火焰元素相关反应后，旅行者将恢复14点暗夜灵魂值。每次激活元素技能流火剑，通过这种方式最多可以恢复28点夜魂值。"
    ),
    effect(
      3,
      "燧原の烽火",
      "Hibara's beacon",
      "桧原的灯塔",
      "「グーシィ・トース」が化けた「蝕まれし源焔の主」と戦う時、旅人の炎元素ダメージ+40%。【源火の玉座に奉納後】元素スキル流火の剣のスキルLv.+3。最大Lv.15まで。",
      'When fighting the transformed "Lord of the Corrupted Flame", the traveler\'s fire elemental damage will be increased by 40%. [After offering to the Throne of Source Fire] Elemental skill Flowing Fire Sword skill Lv. +3. Up to maximum Lv.15.',
      "与变身后的“腐化之炎之主”战斗时，旅者的火元素伤害增加40%。 【献祭源火王座后】元素技能流火剑技能Lv.1 +3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "灼熱の烈火",
      "scorching flame",
      "灼热的火焰",
      "「グーシィ・トース」が化けた「蝕まれし源焔の主」と戦う時、元素爆発燎原の灼炎を発動した後、周囲のチーム全員のHPを、それぞれ回復を受けるキャラのHP上限の40%分回復する。さらに、次の10秒間、旅人の元素エネルギーを1秒毎に4ポイント回復する。【源火の玉座に奉納後】元素爆発燎原の灼炎を発動した後、旅人の炎元素ダメージ+20%、継続時間9秒。",
      'When "Goosey Toth" fights the transformed "Lord of the Corrupted Flames", after activating the Elemental Explosion Burning Flame, the HP of all surrounding team members will be restored by 40% of the maximum HP of the character receiving the recovery. Additionally, for the next 10 seconds, the traveler\'s elemental energy is restored by 4 points every second. [After offering to the Throne of Source Fire] After activating the Elemental Explosion Burning Flame of the Source, the traveler\'s fire elemental damage +20%, duration 9 seconds.',
      "“古西托斯”与变身的“腐化烈焰领主”战斗时，激活元素爆燃烈焰后，周围所有队员的生命值将恢复角色最大生命值的40%。此外，在接下来的10秒内，旅行者的元素能量每秒恢复4点。 【献祭本源之火王座后】激活本源元素爆燃之炎后，旅者的火元素伤害+20%，持续9秒。"
    ),
    effect(
      5,
      "不滅の薪火",
      "immortal firewood",
      "不朽的柴火",
      "「グーシィ・トース」が化けた「蝕まれし源焔の主」と戦う時、旅人の会心率+20%、会心ダメージ+40%。【源火の玉座に奉納後】元素爆発燎原の灼炎のスキルLv.+3。最大Lv.15まで。",
      'When fighting the transformed "Lord of the Corrupted Flame", the traveler\'s critical rate +20% and critical damage +40%. [After offering to the Throne of Source Fire] Elemental Explosion Burning Flame Skill Lv. +3. Up to maximum Lv.15.',
      "与变身后的“腐化之炎之主”战斗时，旅者暴击率+20%，暴击伤害+40%。 【献祭源火王座后】元素爆燃炎技能Lv.1 +3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "永燃の聖火",
      "eternal burning torch",
      "永恒燃烧的火炬",
      "「グーシィ・トース」が化けた「蝕まれし源焔の主」と戦う時、夜魂の加護状態にある場合、旅人の移動速度+20%、スタミナ消費-30%。さらに通常攻撃または重撃を行う時、前方に流火を放ち、経路上の敵に旅人の攻撃力96%分の夜魂性質の炎元素ダメージを与える。【源火の玉座に奉納後】夜魂の加護状態にある時、旅人の通常攻撃、重撃、落下攻撃ダメージは元素付与によって他の元素に変化しない夜魂性質の炎元素ダメージへと変わり、かつそれらの攻撃の会心ダメージ+40%.",
      "When fighting the transformed \"Lord of the Corrupted Flames\", if under the protection of the Night Spirit, the traveler's movement speed increases by 20% and stamina consumption decreases by 30%. Furthermore, when performing a normal attack or heavy attack, it releases a stream of fire in front of it, dealing night spirit elemental fire damage equal to 96% of the traveler's attack power to enemies along the way. [After offering to the Throne of Source Fire] When under the protection of the night soul, the traveler's normal attack, heavy attack, and falling attack damage will change to fire elemental damage of the night soul nature that does not change to other elements due to the addition of elements, and the critical damage of these attacks will be +40%.",
      "与变身的“腐化烈焰领主”战斗时，在夜灵的保护下，旅者的移动速度增加20%，体力消耗减少30%。此外，在进行普通攻击或重击时，它会在前方释放一道火焰流，对沿途敌人造成相当于旅者攻击力96%的夜灵元素火焰伤害。 【献祭本源火王座后】在夜魂的保护下，旅者的普通攻击、重击、坠落攻击伤害将转变为夜魂性质的火元素伤害，不会因元素的加成而转变为其他元素，且这些攻击的暴击伤害+40%。"
    ),
  ],
};

const entry34: Batch17ConstellationEntry = {
  gameVersion: "7.0",
  dataAsOf: "2026-09-08",
  updatedAt: "2026-09-08",
  sourceLabel: t(
    "Game8の2026-09-08確認済み個別ガイドを照合",
    "Cross-checked against the Game8 character guide reviewed on 2026-09-08",
    "已对照2026-09-08确认的Game8角色指南"
  ),
  sourceUrl: "https://game8.jp/genshin/783868",
  effects: [
    effect(
      1,
      "静まりゆく結氷",
      "The calming ice",
      "平静的冰",
      "旅人が星反応ダメージを与えた時、自身の元素エネルギーを5ポイント回復する。この効果は0.5秒毎に1回のみ発動可能。",
      "When the traveler deals star reaction damage, he recovers 5 points of elemental energy. This effect can only be activated once every 0.5 seconds.",
      "当旅行者造成星星反应伤害时，他会恢复5点元素能量。该效果每0.5秒只能启动一次。"
    ),
    effect(
      2,
      "唸る隕氷",
      "Roaring meteorite",
      "咆哮的陨石",
      "元素スキル霧氷の剣で放った氷晶が敵に命中した後、さらに現在フィールド上にいるキャラクターの元素熟知を60アップさせる。継続時間5秒。また、上記効果の影響を受けたキャラクターが星反応を起こしたとき、または星反応ダメージを与えたとき、継続時間中、上記効果は元素熟知を120アップさせるものに変わる。",
      "After the ice crystals released by the elemental skill Rime Sword hit an enemy, the elemental proficiency of characters currently on the field will be increased by 60. Duration: 5 seconds. Also, when a character affected by the above effect causes a star reaction or deals star reaction damage, the above effect changes to one that increases elemental proficiency by 120 for the duration.",
      "元素技能霜剑释放的冰晶击中敌人后，场上角色的元素熟练度增加60点。持续时间：5秒。此外，当受到上述效果影响的角色引起星星反应或造成星星反应伤害时，上述效果将变为在持续时间内增加元素熟练度120的效果。"
    ),
    effect(
      3,
      "断ちきる鋭氷",
      "Cutting sharp ice",
      "切割锋利的冰",
      "元素爆発飛氷の鋒のスキルLv.+3。最大Lv.15まで。",
      "Elemental Explosion Flying Ice Feng skill level +3. Up to maximum Lv.15.",
      "元爆飞冰锋技能等级+3。最高可达 Lv.15。"
    ),
    effect(
      4,
      "溶けざる堅氷",
      "solid ice that doesn't melt",
      "不融化的固体冰",
      "元素スキル霧氷の剣が生成した凛冽の寒星の存在時間が25%延長される。",
      "The duration of Rin's cold star generated by the elemental skill Rime Sword will be extended by 25%.",
      "元素技能霜剑产生的凛寒星持续时间延长25%。"
    ),
    effect(
      5,
      "凍てつく霧氷",
      "freezing rime",
      "霜冻",
      "元素スキル霧氷の剣のスキルLv.+3。最大Lv.15まで。",
      "Elemental skill Rime sword skill Lv. +3. Up to maximum Lv.15.",
      "元素技能雾凇剑技Lv. +3。最高可达 Lv.15。"
    ),
    effect(
      6,
      "殺める輝氷",
      "Killing shining ice",
      "杀死闪亮的冰",
      "元素爆発飛氷の鋒を発動時、寒光を1層消費するごとに、チーム内の他のキャラクターが与える星反応ダメージが5%アップする。この方法によるダメージアップは最大40%まで。継続時間15秒。",
      "When activating Elemental Explosive Flying Ice Wing, each layer of cold light consumed increases star reaction damage dealt by other characters on the team by 5%. This method increases damage by up to 40%. Duration: 15 seconds.",
      "元素爆飞冰翼发动时，每消耗一层寒光，队伍中其他角色造成的星动伤害就会增加5%。此方法最多可增加 40% 的伤害。持续时间：15 秒。"
    ),
  ],
};

export const BATCH_17_CONSTELLATIONS: Record<
  string,
  Batch17ConstellationEntry
> = {
  "genshin:10000020": entry1,
  "genshin:10000045": entry2,
  "genshin:10000064": entry3,
  "genshin:10000048": entry4,
  "genshin:10000092": entry5,
  "genshin:10000037": entry6,
  "genshin:10000093": entry7,
  "genshin:10000027": entry8,
  "genshin:10000056": entry9,
  "genshin:10000057": entry10,
  "genshin:10000042": entry11,
  "genshin:10000054": entry12,
  "genshin:10000059": entry13,
  "genshin:10000035": entry14,
  "genshin:10000036": entry15,
  "genshin:10000063": entry16,
  "genshin:10000002": entry17,
  "genshin:10000066": entry18,
  "genshin:10000044": entry19,
  "genshin:10000094": entry20,
  "genshin:10000053": entry21,
  "genshin:10000075": entry22,
  "genshin:10000024": entry23,
  "genshin:10000109": entry24,
  "genshin:10000108": entry25,
  "genshin:10000061": entry26,
  "genshin:10000026": entry27,
  "genshin:10000005": entry28,
  "genshin:10000007": entry28,
  "genshin:10000005-504": entry28,
  "genshin:10000007-704": entry28,
  "genshin:10000005-506": entry29,
  "genshin:10000007-706": entry29,
  "genshin:10000005-507": entry30,
  "genshin:10000007-707": entry30,
  "genshin:10000005-508": entry31,
  "genshin:10000007-708": entry31,
  "genshin:10000005-501": entry32,
  "genshin:10000007-701": entry32,
  "genshin:10000005-502": entry33,
  "genshin:10000007-702": entry33,
  "genshin:10000005-503": entry34,
  "genshin:10000007-703": entry34,
};
