import type { Team } from "./types";

// 第25バッチ。3起点8案を、同じ4名構成を統合した7マスタへ移行。
// 採否と出典差分はdocs/batch-25-research-notes.md。未確認の別名はIDへ結び付けない。
export const BATCH25_TEAMS: Team[] = [
  {
    id: "team-hsr-千冶・刃-b25-1",
    game: "hsr",
    origin: "千冶・刃",
    originOrder: 1,
    shared: true,
    batch: 25,
    title: {"ja":"不死途・追加攻撃連携","en":"Follow-ups with 不死途","zh-CN":"不死途追加攻击联动"},
    members: [
      {"name":{"ja":"千冶・刃","en":"千冶・刃","zh-CN":"千冶・刃"},"role":{"ja":"HP消費アタッカー・デバフ","en":"HP-consuming DPS / debuffs","zh-CN":"消耗生命输出与减益"}},
      {"name":{"ja":"不死途","en":"不死途","zh-CN":"不死途"},"role":{"ja":"追加攻撃アタッカー・防御低下","en":"Follow-up DPS / DEF reduction","zh-CN":"追加攻击输出与减防"}},
      {"name":{"ja":"トリビー","en":"トリビー","zh-CN":"トリビー"},"role":{"ja":"全体支援・追加攻撃","en":"Team support / follow-ups","zh-CN":"全队辅助与追加攻击"}},
      {"name":{"ja":"ヒアンシー","en":"ヒアンシー","zh-CN":"ヒアンシー"},"role":{"ja":"回復・HP支援","en":"Healing / HP support","zh-CN":"治疗与生命辅助"}},
    ],
    synergy: [{"ja":"千冶・刃と不死途が防御低下と追加攻撃で相互に支援する。トリビーの攻撃で手数を増やし、ヒアンシーがHP消費を回復する。","en":"千冶・刃 and 不死途 support each other through DEF reduction and follow-ups. Tribbie adds attacks, while Hyacine heals HP consumption.","zh-CN":"千冶・刃与不死途通过减防和追加攻击互相辅助。缇宝增加攻击次数，ヒアンシー治疗生命消耗。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-10-03",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://game8.jp/houkaistarrail/776920",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://game8.jp/houkaistarrail/756950","checkedAt":"2026-10-03","status":"crossChecked","note":{"ja":"本文の同じ4名構成を確認。","en":"Confirmed the same four-member roster in the article.","zh-CN":"确认正文相同四人阵容。"}}],
    sourceBatch: 18,
  },
  {
    id: "team-hsr-千冶・刃-b25-2",
    game: "hsr",
    origin: "千冶・刃",
    originOrder: 2,
    shared: true,
    batch: 25,
    title: {"ja":"黄泉・虚無2枠支援","en":"Acheron with two Nihility allies","zh-CN":"黄泉双虚无辅助"},
    members: [
      {"name":{"ja":"千冶・刃","en":"千冶・刃","zh-CN":"千冶・刃"},"role":{"ja":"HP消費アタッカー・デバフ","en":"HP-consuming DPS / debuffs","zh-CN":"消耗生命输出与减益"}},
      {"name":{"ja":"黄泉","en":"黄泉","zh-CN":"黄泉"},"role":{"ja":"必殺技アタッカー","en":"Ultimate DPS","zh-CN":"终结技输出"}},
      {"name":{"ja":"サフェル","en":"サフェル","zh-CN":"サフェル"},"role":{"ja":"デバフ・追加攻撃","en":"Debuffs / follow-ups","zh-CN":"减益与追加攻击"}},
      {"name":{"ja":"ヒアンシー","en":"ヒアンシー","zh-CN":"ヒアンシー"},"role":{"ja":"回復・HP支援","en":"Healing / HP support","zh-CN":"治疗与生命辅助"}},
    ],
    synergy: [{"ja":"千冶・刃の結界中は味方の攻撃でデバフを付与し、黄泉の必殺技回転を助ける。千冶・刃とサフェルで黄泉以外の虚無2枠を確保し、ヒアンシーがHP消費を回復する。","en":"During 千冶・刃’s field, allied attacks apply debuffs to charge Acheron’s Ultimate. 千冶・刃 and Cipher provide two other Nihility allies; Hyacine heals HP consumption.","zh-CN":"千冶・刃结界期间，队友攻击施加减益并为黄泉终结技充能。千冶・刃与赛飞儿提供黄泉以外的双虚无，ヒアンシー回复消耗的生命。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-10-03",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://game8.jp/houkaistarrail/776920",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://gamewith.jp/houkaistarrail/article/show/553897","checkedAt":"2026-10-03","status":"crossChecked","note":{"ja":"本文の同じ4名構成を確認。","en":"Confirmed the same four-member roster in the article.","zh-CN":"确认正文相同四人阵容。"}}],
    sourceBatch: 18,
  },
  {
    id: "team-hsr-千冶・刃-b25-3",
    game: "hsr",
    origin: "千冶・刃",
    originOrder: 3,
    shared: true,
    batch: 25,
    title: {"ja":"姫子・旅立ちの殲滅・Wアタッカー","en":"姫子・旅立ち Annihilation / dual DPS","zh-CN":"姫子・旅立ち歼灭双输出"},
    members: [
      {"name":{"ja":"千冶・刃","en":"千冶・刃","zh-CN":"千冶・刃"},"role":{"ja":"HP消費アタッカー・デバフ","en":"HP-consuming DPS / debuffs","zh-CN":"消耗生命输出与减益"}},
      {"name":{"ja":"姫子・旅立ち","en":"姫子・旅立ち","zh-CN":"姫子・旅立ち"},"role":{"ja":"裁決・殲滅アタッカー","en":"Judgment / Annihilation DPS","zh-CN":"裁决与歼灭输出"}},
      {"name":{"ja":"ヴェルト","en":"ヴェルト","zh-CN":"ヴェルト"},"role":{"ja":"殲滅切替・防御低下","en":"Annihilation activation / DEF reduction","zh-CN":"歼灭切换与减防"}},
      {"name":{"ja":"フォフォ","en":"フォフォ","zh-CN":"フォフォ"},"role":{"ja":"回復・EP支援","en":"Healing / Energy support","zh-CN":"治疗与能量辅助"}},
    ],
    synergy: [{"ja":"ヴェルトが姫子・旅立ちの支援スキルを使い、殲滅モードへ移行する。姫子・旅立ちと千冶・刃が攻撃を重ね、ヴェルトが防御低下、フォフォが回復とEP回復で支える。","en":"Welt uses 姫子・旅立ち’s assist skill to enter Annihilation mode. 姫子・旅立ち and 千冶・刃 attack together, supported by Welt’s DEF reduction and Huohuo’s healing and Energy recovery.","zh-CN":"瓦尔特使用姫子・旅立ち的支援技能进入歼灭模式。姫子・旅立ち与千冶・刃协同攻击，瓦尔特减防，藿藿治疗并回复能量。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-10-02",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://gamewith.jp/houkaistarrail/article/show/553897",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://game8.jp/houkaistarrail/524692","checkedAt":"2026-10-03","status":"crossChecked","note":{"ja":"本文の同じ4名構成を確認。","en":"Confirmed the same four-member roster in the article.","zh-CN":"确认正文相同四人阵容。"}}],
    sourceBatch: 18,
  },
  {
    id: "team-hsr-姫子・旅立ち-b25-1",
    game: "hsr",
    origin: "姫子・旅立ち",
    originOrder: 1,
    shared: true,
    batch: 25,
    title: {"ja":"殲滅・夏ロビンとヴェルト","en":"Annihilation with summer Robin and Welt","zh-CN":"夏日知更鸟与瓦尔特歼灭队"},
    members: [
      {"name":{"ja":"姫子・旅立ち","en":"姫子・旅立ち","zh-CN":"姫子・旅立ち"},"role":{"ja":"裁決・殲滅アタッカー","en":"Judgment / Annihilation DPS","zh-CN":"裁决与歼灭输出"}},
      {"name":{"ja":"ロビン・夏空の歌","en":"ロビン・夏空の歌","zh-CN":"ロビン・夏空の歌"},"role":{"ja":"EP回復・火力支援","en":"Energy recovery / damage support","zh-CN":"能量回复与输出辅助"}},
      {"name":{"ja":"ヴェルト","en":"ヴェルト","zh-CN":"ヴェルト"},"role":{"ja":"殲滅切替・防御低下","en":"Annihilation activation / DEF reduction","zh-CN":"歼灭切换与减防"}},
      {"name":{"ja":"フォフォ","en":"フォフォ","zh-CN":"フォフォ"},"role":{"ja":"回復・EP支援","en":"Healing / Energy support","zh-CN":"治疗与能量辅助"}},
    ],
    synergy: [{"ja":"ヴェルトの支援スキルで殲滅モードへ移行し、夏ロビンとヴェルトが全体火力を支える。フォフォが回復とEP回復を担当する。GameWith掲載のフォフォ案を採用し、Game8の丹恒・騰荒案とは区別する。","en":"Welt’s assist skill activates Annihilation mode; summer Robin and Welt support team damage. Huohuo heals and restores Energy. This follows GameWith’s Huohuo roster, distinct from Game8’s Dan Heng variant.","zh-CN":"瓦尔特支援技能启动歼灭模式，夏日知更鸟与瓦尔特辅助全队输出，藿藿治疗并回复能量。采用GameWith的藿藿阵容，与Game8的丹恒・騰荒方案区分。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-10-02",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://gamewith.jp/houkaistarrail/article/show/561096",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://game8.jp/houkaistarrail/784730","checkedAt":"2026-10-03","status":"watching","note":{"ja":"役割と条件を確認。掲載メンバーが異なるため同構成の照合済みとはしない。","en":"Checked roles and conditions; differing published members do not verify this exact roster.","zh-CN":"核对角色定位及条件；刊载成员不同，不视为相同阵容已核对。"}}],
    sourceBatch: 18,
  },
  {
    id: "team-hsr-姫子・旅立ち-b25-2",
    game: "hsr",
    origin: "姫子・旅立ち",
    originOrder: 2,
    shared: true,
    batch: 25,
    title: {"ja":"裁決・サンデー行動支援","en":"Judgment with Sunday action support","zh-CN":"星期日行动辅助裁决队"},
    members: [
      {"name":{"ja":"姫子・旅立ち","en":"姫子・旅立ち","zh-CN":"姫子・旅立ち"},"role":{"ja":"裁決・殲滅アタッカー","en":"Judgment / Annihilation DPS","zh-CN":"裁决与歼灭输出"}},
      {"name":{"ja":"サンデー","en":"サンデー","zh-CN":"サンデー"},"role":{"ja":"行動・EP支援","en":"Action / Energy support","zh-CN":"行动与能量辅助"}},
      {"name":{"ja":"ロビン・夏空の歌","en":"ロビン・夏空の歌","zh-CN":"ロビン・夏空の歌"},"role":{"ja":"EP回復・火力支援","en":"Energy recovery / damage support","zh-CN":"能量回复与输出辅助"}},
      {"name":{"ja":"丹恒・騰荒","en":"丹恒・騰荒","zh-CN":"丹恒・騰荒"},"role":{"ja":"バリア・攻撃力支援","en":"Shields / ATK support","zh-CN":"护盾与攻击辅助"}},
    ],
    synergy: [{"ja":"サンデーまたは丹恒・騰荒の支援スキルで裁決モードへ移行する。サンデーが行動を支援し、夏ロビンがEPと火力、丹恒・騰荒がバリアで支える。GameWithの花火入り案とは異なる構成。","en":"Sunday or Dan Heng uses the assist skill to activate Judgment mode. Sunday advances actions, summer Robin supports Energy and damage, and Dan Heng shields. This differs from GameWith’s Sparkle roster.","zh-CN":"星期日或丹恒・騰荒使用支援技能启动裁决模式。星期日辅助行动，夏日知更鸟支援能量与输出，丹恒・騰荒提供护盾。与GameWith的花火阵容不同。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-10-03",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://game8.jp/houkaistarrail/784730",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://gamewith.jp/houkaistarrail/article/show/561096","checkedAt":"2026-10-03","status":"watching","note":{"ja":"役割と条件を確認。掲載メンバーが異なるため同構成の照合済みとはしない。","en":"Checked roles and conditions; differing published members do not verify this exact roster.","zh-CN":"核对角色定位及条件；刊载成员不同，不视为相同阵容已核对。"}}],
    sourceBatch: 18,
  },
  {
    id: "team-hsr-姫子・旅立ち-b25-3",
    game: "hsr",
    origin: "姫子・旅立ち",
    originOrder: 3,
    shared: true,
    batch: 25,
    title: {"ja":"裁決・記憶主人公支援","en":"Judgment with Remembrance Trailblazer","zh-CN":"记忆开拓者辅助裁决队"},
    members: [
      {"name":{"ja":"姫子・旅立ち","en":"姫子・旅立ち","zh-CN":"姫子・旅立ち"},"role":{"ja":"裁決・殲滅アタッカー","en":"Judgment / Annihilation DPS","zh-CN":"裁决与歼灭输出"}},
      {"name":{"ja":"開拓者（記憶）","en":"開拓者（記憶）","zh-CN":"開拓者（記憶）"},"role":{"ja":"行動支援","en":"Action support","zh-CN":"行动辅助"}},
      {"name":{"ja":"ルアン・メェイ","en":"ルアン・メェイ","zh-CN":"ルアン・メェイ"},"role":{"ja":"全体火力・撃破支援","en":"Team damage / Break support","zh-CN":"全队输出与击破辅助"}},
      {"name":{"ja":"フォフォ","en":"フォフォ","zh-CN":"フォフォ"},"role":{"ja":"回復・EP支援","en":"Healing / Energy support","zh-CN":"治疗与能量辅助"}},
    ],
    synergy: [{"ja":"記憶主人公の支援スキルで裁決モードへ移行する。記憶主人公の行動支援とルアン・メェイの全体支援を重ね、フォフォが回復とEP回復を担当する。","en":"The Remembrance Trailblazer’s assist skill activates Judgment mode. Trailblazer action support and Ruan Mei’s team buffs combine with Huohuo’s healing and Energy recovery.","zh-CN":"记忆开拓者的支援技能启动裁决模式，叠加开拓者行动辅助与阮·梅全队增益，藿藿提供治疗和能量回复。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-10-02",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://gamewith.jp/houkaistarrail/article/show/561096",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://game8.jp/houkaistarrail/784730","checkedAt":"2026-10-03","status":"watching","note":{"ja":"役割と条件を確認。掲載メンバーが異なるため同構成の照合済みとはしない。","en":"Checked roles and conditions; differing published members do not verify this exact roster.","zh-CN":"核对角色定位及条件；刊载成员不同，不视为相同阵容已核对。"}}],
    sourceBatch: 18,
  },
  {
    id: "team-hsr-不死途-b25-1",
    game: "hsr",
    origin: "不死途",
    originOrder: 1,
    shared: true,
    batch: 25,
    title: {"ja":"不死途・行動支援キャリー","en":"不死途 carry with action support","zh-CN":"不死途行动辅助核心队"},
    members: [
      {"name":{"ja":"不死途","en":"不死途","zh-CN":"不死途"},"role":{"ja":"追加攻撃アタッカー・防御低下","en":"Follow-up DPS / DEF reduction","zh-CN":"追加攻击输出与减防"}},
      {"name":{"ja":"サンデー","en":"サンデー","zh-CN":"サンデー"},"role":{"ja":"行動・EP支援","en":"Action / Energy support","zh-CN":"行动与能量辅助"}},
      {"name":{"ja":"トリビー","en":"トリビー","zh-CN":"トリビー"},"role":{"ja":"全体支援・追加攻撃","en":"Team support / follow-ups","zh-CN":"全队辅助与追加攻击"}},
      {"name":{"ja":"丹恒・騰荒","en":"丹恒・騰荒","zh-CN":"丹恒・騰荒"},"role":{"ja":"バリア・攻撃力支援","en":"Shields / ATK support","zh-CN":"护盾与攻击辅助"}},
    ],
    synergy: [{"ja":"サンデーが不死途の行動を支援する。不死途の必殺技からトリビーの追加攻撃へつなぎ、さらに不死途の追加攻撃を促す。丹恒・騰荒がバリアと攻撃力支援を担当する。","en":"Sunday supports 不死途’s actions. 不死途’s Ultimate triggers Tribbie’s follow-up, which enables another 不死途 follow-up. Dan Heng provides shields and ATK support.","zh-CN":"星期日辅助不死途行动。不死途终结技触发缇宝追加攻击，再促进不死途追加攻击。丹恒・騰荒提供护盾与攻击辅助。"}],
    targetSummary: {"ja":"編成・光円錐・星魂の戦闘中効果は公開プロフィールへ加算しない。","en":"Combat effects from teams, Light Cones, and Eidolons are excluded from public-profile stats.","zh-CN":"配队、光锥与星魂的战斗内效果不计入公开面板。"},
    gameVersion: "4.6",
    dataAsOf: "2026-09-29",
    updatedAt: "2026-10-03",
    sourceLabel: {"ja":"個別ガイドの実名4名構成を確認（2026-10-03）","en":"Four-member character-guide roster checked 2026-10-03","zh-CN":"角色指南四人阵容核对于2026-10-03"},
    sourceUrl: "https://game8.jp/houkaistarrail/756950",
    communitySources: [{"label":{"ja":"別の個別ガイドで再確認","en":"Additional character guide","zh-CN":"其他角色指南"},"url":"https://game8.jp/houkaistarrail/642577","checkedAt":"2026-10-03","status":"watching","note":{"ja":"役割と条件を確認。掲載メンバーが異なるため同構成の照合済みとはしない。","en":"Checked roles and conditions; differing published members do not verify this exact roster.","zh-CN":"核对角色定位及条件；刊载成员不同，不视为相同阵容已核对。"}}],
    sourceBatch: 16,
  },
];
